// examples/web/preact/ssr-examples/ssr/src/components/SearchForm.tsx
import { useId, useState } from "preact/hooks";

import type { JSX } from "preact";

// Preact's `useId()` (since `preact-render-to-string@6.6.5`, Dec 2025)
// returns a stable per-component-instance ID. SSR and client produce
// identical values, so the a11y contract `<label htmlFor={...}>` ↔
// `<input id={...}>` survives hydration without warnings.
//
// Without useId(): Math.random/Date.now/counter all break under SSR
// because server and client render in different processes / different
// times. useId() is the canonical fix — same hook name as React 18+.
export function SearchForm(): JSX.Element {
  const queryId = useId();
  const sortId = useId();
  const [query, setQuery] = useState("");
  const [sort, setSort] = useState<"asc" | "desc">("asc");

  return (
    <form data-testid="search-form" onSubmit={(e) => e.preventDefault()}>
      <fieldset>
        <legend>Search</legend>

        <div>
          <label htmlFor={queryId} data-testid="query-label">
            Search query
          </label>
          <input
            id={queryId}
            type="text"
            value={query}
            onInput={(e) => setQuery((e.target as HTMLInputElement).value)}
            data-testid="query-input"
          />
        </div>

        <div>
          <label htmlFor={sortId} data-testid="sort-label">
            Sort order
          </label>
          <select
            id={sortId}
            value={sort}
            onChange={(e) =>
              setSort((e.target as HTMLSelectElement).value as "asc" | "desc")
            }
            data-testid="sort-select"
          >
            <option value="asc">Ascending</option>
            <option value="desc">Descending</option>
          </select>
        </div>
      </fieldset>
    </form>
  );
}

// examples/web/vue/ssr-examples/ssr/src/components/SearchForm.vue
<script setup lang="ts">
import { useId, ref } from "vue";

// Vue 3.5's `useId()` returns a stable per-component-instance ID.
// On SSR, every render produces deterministic IDs; the client
// hydration walker sees the same IDs and matches them, so label[for]
// pointers don't break across the SSR→CSR boundary.
//
// Why hand-rolled IDs (Math.random, counter++, crypto.randomUUID)
// fail under SSR:
//   - Math.random differs between server and client → hydration
//     mismatch warnings.
//   - A module-level counter resets between requests on long-lived
//     workers, but worse: the SAME counter advances per request
//     across concurrent renders, leaking state.
//   - crypto.randomUUID changes per call.
//
// useId() solves all three: deterministic, per-instance, request-
// isolated. Maps to React's useId / Solid's createUniqueId.
const queryId = useId();
const sortId = useId();
const query = ref("");
const sort = ref<"asc" | "desc">("asc");
</script>

<template>
  <form data-testid="search-form" @submit.prevent>
    <fieldset>
      <legend>Search</legend>

      <div>
        <label :for="queryId" data-testid="query-label">Search query</label>
        <input
          :id="queryId"
          v-model="query"
          type="text"
          data-testid="query-input"
        />
      </div>

      <div>
        <label :for="sortId" data-testid="sort-label">Sort order</label>
        <select :id="sortId" v-model="sort" data-testid="sort-select">
          <option value="asc">Ascending</option>
          <option value="desc">Descending</option>
        </select>
      </div>
    </fieldset>
  </form>
</template>
