// examples/preact/combined/src/App.tsx
import { getDependenciesApi, getRoutesApi } from "@real-router/core/api";
import { RouteView, useNavigator } from "@real-router/preact";
import { lazy } from "preact/compat";
import { useSyncExternalStore } from "preact/compat";

import { ProgressBar } from "./components/ProgressBar";
import { Admin } from "./pages/Admin";
import { Checkout } from "./pages/Checkout";
import { Home } from "./pages/Home";
import { Login } from "./pages/Login";
import { ProductDetail } from "./pages/ProductDetail";
import { ProductList } from "./pages/ProductList";
import { Settings } from "./pages/Settings";
import { UsersLayout } from "./pages/UsersLayout";
import { router } from "./router";
import { publicRoutes, privateRoutes } from "./routes";
import { defineAbilities } from "../../../shared/abilities";
import { store } from "../../../shared/store";
import { Layout } from "../../shared/Layout";

import type { User } from "../../../shared/api";
import type { JSX } from "preact";

const LazyDashboard = lazy(() => import("./pages/Dashboard"));

export function App(): JSX.Element {
  const navigator = useNavigator();

  const user = useSyncExternalStore(
    store.subscribe,
    () => store.get("user") as User | null,
  );

  const privateLinks = [
    { routeName: "dashboard", label: "Dashboard" },
    { routeName: "products", label: "Products" },
    { routeName: "users", label: "Users" },
    { routeName: "settings", label: "Settings" },
    { routeName: "admin", label: "Admin" },
    { routeName: "checkout", label: "Checkout" },
  ];

  const publicLinks = [
    { routeName: "home", label: "Home" },
    { routeName: "login", label: "Login" },
  ];

  const links = user ? privateLinks : publicLinks;

  const onLogin = async (loggedInUser: User) => {
    store.set("user", loggedInUser);
    getDependenciesApi(router).set(
      "abilities",
      defineAbilities(loggedInUser.role),
    );
    const routesApi = getRoutesApi(router);

    routesApi.clear();
    routesApi.add(privateRoutes);
    await navigator.navigate("dashboard");
  };

  const onLogout = async () => {
    store.set("user", null);
    getDependenciesApi(router).set("abilities", []);
    const routesApi = getRoutesApi(router);

    routesApi.clear();
    routesApi.add(publicRoutes);
    await navigator.navigate("home");
  };

  return (
    <Layout title="Real-Router — Combined" links={links}>
      <ProgressBar />
      <RouteView nodeName="">
        <RouteView.Match segment="home">
          <Home />
        </RouteView.Match>
        <RouteView.Match segment="login">
          <Login onLogin={onLogin} />
        </RouteView.Match>
        <RouteView.Match
          segment="dashboard"
          fallback={<span className="spinner" />}
        >
          <LazyDashboard onLogout={onLogout} />
        </RouteView.Match>
        <RouteView.Match segment="products">
          <RouteView nodeName="products">
            <RouteView.Match segment="list">
              <ProductList />
            </RouteView.Match>
            <RouteView.Match segment="detail">
              <ProductDetail />
            </RouteView.Match>
          </RouteView>
        </RouteView.Match>
        <RouteView.Match segment="users">
          <UsersLayout />
        </RouteView.Match>
        <RouteView.Match segment="settings">
          <Settings />
        </RouteView.Match>
        <RouteView.Match segment="admin">
          <Admin />
        </RouteView.Match>
        <RouteView.Match segment="checkout">
          <Checkout />
        </RouteView.Match>
        <RouteView.NotFound>
          <h1>404 — Page Not Found</h1>
          <p>The page you are looking for does not exist.</p>
          <p>Try logging in — available routes change based on auth state.</p>
        </RouteView.NotFound>
      </RouteView>
    </Layout>
  );
}

// examples/web/svelte/combined/src/App.svelte
<script lang="ts">
  import { getDependenciesApi, getRoutesApi } from "@real-router/core/api";
  import { RouterProvider, RouteView } from "@real-router/svelte";
  import type { Router } from "@real-router/core";
  import Layout from "../../shared/Layout.svelte";
  import ProgressBar from "./components/ProgressBar.svelte";
  import Home from "./pages/Home.svelte";
  import Login from "./pages/Login.svelte";
  import Dashboard from "./pages/Dashboard.svelte";
  import ProductList from "./pages/ProductList.svelte";
  import ProductDetail from "./pages/ProductDetail.svelte";
  import UsersLayout from "./pages/UsersLayout.svelte";
  import Settings from "./pages/Settings.svelte";
  import Admin from "./pages/Admin.svelte";
  import Checkout from "./pages/Checkout.svelte";
  import { publicRoutes, privateRoutes } from "./routes";
  import { defineAbilities } from "../../../shared/abilities";
  import { store } from "../../../shared/store";

  import type { User } from "../../../shared/api";
  import type { AppDependencies } from "./types";

  let { router }: { router: Router<AppDependencies> } = $props();

  let user = $state(store.get("user") as User | null);

  $effect(() => {
    return store.subscribe(() => {
      user = store.get("user") as User | null;
    });
  });

  const links = $derived(
    user
      ? [
          { routeName: "dashboard", label: "Dashboard" },
          { routeName: "products", label: "Products" },
          { routeName: "users", label: "Users" },
          { routeName: "settings", label: "Settings" },
          { routeName: "admin", label: "Admin" },
          { routeName: "checkout", label: "Checkout" },
        ]
      : [
          { routeName: "home", label: "Home" },
          { routeName: "login", label: "Login" },
        ],
  );

  const onLogin = async (loggedInUser: User) => {
    store.set("user", loggedInUser);
    getDependenciesApi(router).set(
      "abilities",
      defineAbilities(loggedInUser.role),
    );
    const routesApi = getRoutesApi(router);
    routesApi.clear();
    routesApi.add(privateRoutes);
    await router.navigate("dashboard");
  };

  const onLogout = async () => {
    store.set("user", null);
    getDependenciesApi(router).set("abilities", []);
    const routesApi = getRoutesApi(router);
    routesApi.clear();
    routesApi.add(publicRoutes);
    await router.navigate("home");
  };
</script>

<RouterProvider {router} announceNavigation>
  <Layout title="Real-Router — Combined" {links}>
    <ProgressBar />
    <RouteView nodeName="">
      {#snippet home()}
        <Home />
      {/snippet}
      {#snippet login()}
        <Login {onLogin} />
      {/snippet}
      {#snippet dashboard()}
        <Dashboard {onLogout} />
      {/snippet}
      {#snippet products()}
        <RouteView nodeName="products">
          {#snippet list()}
            <ProductList />
          {/snippet}
          {#snippet detail()}
            <ProductDetail />
          {/snippet}
        </RouteView>
      {/snippet}
      {#snippet users()}
        <UsersLayout />
      {/snippet}
      {#snippet settings()}
        <Settings />
      {/snippet}
      {#snippet admin()}
        <Admin />
      {/snippet}
      {#snippet checkout()}
        <Checkout />
      {/snippet}
      {#snippet notFound()}
        <h1>404 — Page Not Found</h1>
        <p>The page you are looking for does not exist.</p>
        <p>Try logging in — available routes change based on auth state.</p>
      {/snippet}
    </RouteView>
  </Layout>
</RouterProvider>
