// benchmarks/cross-router/apps/svelte/sv-router/params/src/ParamLeaf.svelte
<script lang="ts">
  // Count the k-params the matcher extracted for the current route (data-count).
  import { route } from "./router";

  const count = $derived(
    Object.keys(route.params).filter((k) => /^k\d+$/.test(k)).length,
  );
</script>

<main data-testid="page-param" data-count={count}>{count} params</main>

// benchmarks/cross-router/apps/angular/angular-router/params/src/pages/param-leaf.component.ts
import { Component, inject } from "@angular/core";
import { ActivatedRoute } from "@angular/router";

// Counts the path params it received (k1, k2, …) and reports via data-count, so
// the driver can confirm arrival at the N-param route.
@Component({
  selector: "param-leaf-page",
  template: `<main data-testid="page-param" [attr.data-count]="count()">
    {{ count() }} params
  </main>`,
})
export class ParamLeafComponent {
  private readonly route = inject(ActivatedRoute);
  count(): string {
    const n = Object.keys(this.route.snapshot.params).filter((k) =>
      /^k\d+$/.test(k),
    ).length;
    return String(n);
  }
}
