// examples/svelte/reactive-source/src/components/NavigationMonitor.svelte
<script lang="ts">
  import { createReactiveSource, useRouter } from "@real-router/svelte";
  import { createRouteSource, createTransitionSource } from "@real-router/sources";

  const router = useRouter();

  const routeState = createReactiveSource(createRouteSource(router));
  const transitionState = createReactiveSource(createTransitionSource(router));

  let history = $state<string[]>([]);

  $effect(() => {
    const name = routeState.current?.name;
    if (name) {
      history = [...history, `${new Date().toLocaleTimeString()} → ${name}`].slice(-10);
    }
  });
</script>

<div class="card" style="margin-top: 24px">
  <strong>Navigation Monitor</strong>
  <p style="font-size: 13px; color: #888; margin-top: 4px">
    Built with <code>createReactiveSource</code> + <code>createRouteSource</code> / <code>createTransitionSource</code>
  </p>

  <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-top: 12px">
    <div>
      <strong style="font-size: 12px; color: #888">CURRENT ROUTE</strong>
      <div style="margin-top: 4px">
        <p>Name: <strong>{routeState.current?.name ?? "—"}</strong></p>
        <p>Path: <code>{routeState.current?.path ?? "—"}</code></p>
        <p>Params: <code>{JSON.stringify(routeState.current?.params ?? {})}</code></p>
      </div>
    </div>
    <div>
      <strong style="font-size: 12px; color: #888">TRANSITION STATE</strong>
      <div style="margin-top: 4px">
        <p>Transitioning: <strong>{transitionState.current.isTransitioning ? "Yes" : "No"}</strong></p>
        {#if transitionState.current.isTransitioning}
          <div class="progress-bar" style="width: 100%; margin-top: 4px"></div>
        {/if}
      </div>
    </div>
  </div>

  <div style="margin-top: 16px">
    <strong style="font-size: 12px; color: #888">NAVIGATION HISTORY (last 10)</strong>
    {#if history.length === 0}
      <p style="font-size: 13px; color: #888">No navigations yet.</p>
    {:else}
      <ul style="padding-left: 16px; margin-top: 4px">
        {#each history.toReversed() as entry}
          <li style="font-size: 13px">{entry}</li>
        {/each}
      </ul>
    {/if}
  </div>
</div>

// examples/solid/signal-primitives/src/pages/NavigationMonitor.tsx
import {
  createSignalFromSource,
  createStoreFromSource,
  useRouter,
} from "@real-router/solid";
import {
  createRouteSource,
  createTransitionSource,
} from "@real-router/sources";
import { createEffect, createSignal, Show } from "solid-js";

import type { RouteSnapshot } from "@real-router/sources";
import type { JSX } from "solid-js";

export function NavigationMonitor(): JSX.Element {
  const router = useRouter();

  // Low-level: createSignalFromSource for transition state (Accessor-based)
  const transitionSource = createTransitionSource(router);
  const transition = createSignalFromSource(transitionSource);

  // Low-level: createStoreFromSource for route state (store-based, granular)
  const routeSource = createRouteSource(router);
  const routeStore: RouteSnapshot = createStoreFromSource(routeSource);

  // Custom navigation counter — skip initial effect run via prev tracking
  const [navCount, setNavCount] = createSignal(0);
  let initialized = false;

  createEffect(() => {
    // Track route name changes to count navigations
    // eslint-disable-next-line @typescript-eslint/no-unused-expressions
    routeStore.route?.name;
    if (initialized) {
      setNavCount((c) => c + 1);
    }

    initialized = true;
  });

  return (
    <div class="card" style={{ "margin-bottom": "16px", "font-size": "13px" }}>
      <strong>Navigation Monitor (built with low-level primitives)</strong>
      <div
        style={{
          display: "grid",
          "grid-template-columns": "1fr 1fr 1fr",
          gap: "12px",
          "margin-top": "8px",
        }}
      >
        <div>
          <p style={{ color: "#888" }}>Current Route (store)</p>
          <p>
            <strong>{routeStore.route?.name ?? "—"}</strong>
          </p>
        </div>
        <div>
          <p style={{ color: "#888" }}>Previous Route (store)</p>
          <p>
            <strong>{routeStore.previousRoute?.name ?? "—"}</strong>
          </p>
        </div>
        <div>
          <p style={{ color: "#888" }}>Navigation Count</p>
          <p>
            <strong>{navCount()}</strong>
          </p>
        </div>
      </div>
      <Show when={transition().isTransitioning}>
        <p style={{ color: "#1565c0", "margin-top": "8px" }}>
          Transitioning to: {transition().toRoute?.name ?? "?"}
        </p>
      </Show>
      <p style={{ color: "#888", "margin-top": "8px" }}>
        Built with: <code>createSignalFromSource</code> (transition) +{" "}
        <code>createStoreFromSource</code> (route state)
      </p>
    </div>
  );
}
