// packages/solid/src/components/Await.tsx
import { createResource } from "solid-js";

import { useDeferred } from "../hooks/useDeferred";

import type { JSX } from "solid-js";

export interface AwaitProps<T> {
  /** Deferred key declared in the loader's `defer({ deferred: { <name>: ... } })`. */
  readonly name: string;
  /** Render the resolved value. Surrounding `<Suspense>` shows fallback while
   * pending; rejection bubbles through Solid's `<ErrorBoundary>`. */
  readonly children: (value: T) => JSX.Element;
}

/**
 * Reads `useDeferred(name)` and hands the resolved value to the render-prop.
 * Wraps the deferred promise in `createResource` so Solid's reactivity tracks
 * resolution and `<Suspense>` gets the standard suspend signal.
 *
 * ```tsx
 * <Streamed fallback={<Spinner />}>
 *   <Await<Review[]> name="reviews">
 *     {(reviews) => <ReviewList items={reviews} />}
 *   </Await>
 * </Streamed>
 * ```
 *
 * Implementation: returns a Solid accessor (function child) that reads
 * `resource()` — this both (a) triggers `<Suspense>` suspension while pending
 * and (b) re-throws on `errored` for the nearest `<ErrorBoundary>` to catch.
 * The render-prop is gated on `resource.state === "ready"` rather than on
 * truthiness so falsy resolved values (`0`, `false`, `null`, `""`) still
 * reach `props.children`.
 */
export function Await<T = unknown>(props: AwaitProps<T>): JSX.Element {
  const promiseAccessor = useDeferred<T>(props.name);
  const [resource] = createResource(promiseAccessor, (promise) => promise);

  return (() => {
    const value = resource();

    if (resource.state !== "ready") {
      return;
    }

    return props.children(value as T);
  }) as unknown as JSX.Element;
}

// packages/svelte/src/components/Await.svelte
<!--
  @component
  Reads `useDeferred(name)` and renders the `children` snippet with the
  resolved value via Svelte's native `{#await}` block. Optional `fallback`
  snippet shown while the promise is pending; rejection bubbles to the
  nearest `{:catch}` handler in the surrounding `{#await}` chain (or
  `<Streamed>`).

  ```svelte
  <Await name="reviews">
    {#snippet children(reviews)}
      <ReviewList items={reviews} />
    {/snippet}
    {#snippet fallback()}
      <Spinner />
    {/snippet}
  </Await>
  ```
-->
<script lang="ts" generics="T">
  import { useDeferred } from "../composables/useDeferred.svelte";

  import type { Snippet } from "svelte";

  interface Props {
    /** Deferred key declared in the loader's `defer({ deferred: { <name>: ... } })`. */
    name: string;
    /** Render snippet for the resolved value. */
    children: Snippet<[T]>;
    /** Snippet shown while the promise is pending. */
    fallback?: Snippet;
  }

  let { name, children, fallback }: Props = $props();

  // `useDeferred(name)` reads `state.context.ssrDataDeferred[name]` —
  // wrap in `$derived` so a dynamic `name` prop re-resolves the promise
  // (vs. capturing the initial value at component init).
  const promise = $derived(useDeferred<T>(name));
</script>

{#await promise}
  {#if fallback}
    {@render fallback()}
  {/if}
{:then value}
  {@render children(value)}
{/await}
