// examples/web/angular/ssr-examples/ssr-streaming/src/pages/home.component.ts
import { Component } from "@angular/core";
import { RealLink } from "@real-router/angular";

@Component({
  selector: "home-page",
  imports: [RealLink],
  template: `
    <section data-testid="home-page">
      <h1>Streaming SSR Example</h1>
      <p>
        Demonstrates Angular 21
        <code>&#64;defer (on viewport)</code> +
        <code>&#64;defer (on hover)</code> with incremental hydration — wired
        through <code>&#64;real-router/ssr-data-plugin</code> for critical
        product data.
      </p>
      <p>
        <a realLink routeName="products.list" data-testid="nav-products">
          Browse products
        </a>
      </p>
    </section>
  `,
})
export class HomeComponent {}

// examples/web/svelte/ssr-examples/ssr-streaming/src/pages/Home.svelte
<script lang="ts">
  import { Link } from "@real-router/svelte";
</script>

<section data-testid="home-page">
  <h1>Streaming SSR Example</h1>
  <p>
    Demonstrates Svelte 5 async SSR with <code>&lt;svelte:boundary&gt;</code>
    + <code>{`{#await}`}</code> blocks for deferred data — wired through
    <code>@real-router/ssr-data-plugin</code> with
    <strong>zero router-specific streaming API</strong>.
  </p>
  <p>
    <Link routeName="products.list" data-testid="nav-products">
      Browse products
    </Link>
  </p>
</section>
