// examples/web/vue/nested-routes/src/pages/UsersLayout.vue
<script setup lang="ts">
import {
  Link,
  RouteView,
  useRoute,
  useRouteNode,
  useRouteUtils,
} from "@real-router/vue";
import { computed } from "vue";

import UserProfile from "./UserProfile.vue";
import UsersList from "./UsersList.vue";

import type { Params } from "@real-router/core";

const routeLabels: Record<string, string> = {
  home: "Home",
  users: "Users",
  "users.profile.settings": "Settings",
};

function getLabel(name: string, params: Params): string {
  if (name in routeLabels) {
    return routeLabels[name];
  }

  if (name === "users.profile") {
    const id = typeof params.id === "string" ? params.id : "?";

    return `User #${id}`;
  }

  return name;
}

const { route: usersRoute } = useRouteNode("users");
const { route } = useRoute();
const utils = useRouteUtils();

const crumbs = computed(() => {
  const chain = utils.getChain(route.value.name) ?? [route.value.name];

  return ["home", ...chain];
});
</script>

<template>
  <div v-if="usersRoute">
    <nav class="breadcrumbs" aria-label="breadcrumb">
      <template v-for="(name, i) in crumbs" :key="name">
        <span v-if="i > 0"> › </span>
        <span v-if="i === crumbs.length - 1">{{
          getLabel(name, route.params)
        }}</span>
        <Link v-else :routeName="name">{{ getLabel(name, route.params) }}</Link>
      </template>
    </nav>

    <div :style="{ marginTop: '16px' }">
      <!--
        `users` route IS the list — no synthetic `list` child / forwardTo.
        <RouteView.Self> renders UsersList when active route is exactly
        `users`; <RouteView.Match segment="profile"> wins for /users/:id and
        deeper (UserProfile owns its own sub-navigation).
      -->
      <RouteView nodeName="users">
        <RouteView.Self>
          <UsersList />
        </RouteView.Self>
        <RouteView.Match segment="profile">
          <UserProfile />
        </RouteView.Match>
      </RouteView>
    </div>
  </div>
</template>

// examples/web/react/nested-routes/src/pages/UsersLayout.tsx
import {
  Link,
  RouteView,
  useRoute,
  useRouteNode,
  useRouteUtils,
} from "@real-router/react";
import { Fragment } from "react";

import { UserProfile } from "./UserProfile";
import { UsersList } from "./UsersList";

import type { Params } from "@real-router/core";
import type { JSX } from "react";

const routeLabels: Record<string, string> = {
  home: "Home",
  users: "Users",
  "users.profile.settings": "Settings",
};

function getLabel(name: string, params: Params): string {
  if (name in routeLabels) {
    return routeLabels[name];
  }

  if (name === "users.profile") {
    const id = typeof params.id === "string" ? params.id : "?";

    return `User #${id}`;
  }

  return name;
}

function Breadcrumbs(): JSX.Element | null {
  const { route } = useRoute();
  const utils = useRouteUtils();

  if (!route) {
    return null;
  }

  const chain = utils.getChain(route.name) ?? [route.name];
  const crumbs = ["home", ...chain];

  return (
    <nav className="breadcrumbs" aria-label="breadcrumb">
      {crumbs.map((name, i) => {
        const isLast = i === crumbs.length - 1;
        const label = getLabel(name, route.params);

        return (
          <Fragment key={name}>
            {i > 0 && <span> › </span>}
            {isLast ? (
              <span>{label}</span>
            ) : (
              <Link routeName={name}>{label}</Link>
            )}
          </Fragment>
        );
      })}
    </nav>
  );
}

export function UsersLayout(): JSX.Element | null {
  const { route } = useRouteNode("users");

  if (!route) {
    return null;
  }

  return (
    <div>
      <Breadcrumbs />

      <div style={{ marginTop: "16px" }}>
        {/*
          `users` route IS the list — no synthetic `list` child / forwardTo.
          <RouteView.Self> renders UsersList when active route is exactly
          `users`; <RouteView.Match segment="profile"> wins for /users/:id and
          deeper (UserProfile owns its own sub-navigation between profile-info
          and per-user Settings).
        */}
        <RouteView nodeName="users">
          <RouteView.Self>
            <UsersList />
          </RouteView.Self>
          <RouteView.Match segment="profile">
            <UserProfile />
          </RouteView.Match>
        </RouteView>
      </div>
    </div>
  );
}
