// examples/web/angular/combined/src/components/progress-bar.component.ts
import { Component } from "@angular/core";
import { injectRouterTransition } from "@real-router/angular";

@Component({
  selector: "progress-bar",
  template: `
    @if (transition().isTransitioning) {
      <div
        class="progress-bar"
        data-testid="progress-bar"
        style="width: 100%;"
      ></div>
    }
  `,
})
export class ProgressBarComponent {
  readonly transition = injectRouterTransition();
}

// examples/react/combined/src/components/ProgressBar.tsx
import { useRouterTransition } from "@real-router/react";

import type { JSX } from "react";

export function ProgressBar(): JSX.Element | null {
  const { isTransitioning } = useRouterTransition();

  if (!isTransitioning) {
    return null;
  }

  return (
    <div
      className="progress-bar"
      data-testid="progress-bar"
      style={{ width: "100%" }}
    />
  );
}
