// examples/web/solid/async-guards/src/components/ProgressBar.tsx
import { useRouterTransition } from "@real-router/solid";
import { Show } from "solid-js";

import type { JSX } from "solid-js";

export function ProgressBar(): JSX.Element {
  const transition = useRouterTransition();

  return (
    <Show when={transition().isTransitioning}>
      <div class="progress-bar" style={{ width: "100%" }} />
    </Show>
  );
}

// examples/web/preact/async-guards/src/components/ProgressBar.tsx
import { useRouterTransition } from "@real-router/preact";

import type { JSX } from "preact";

export function ProgressBar(): JSX.Element | null {
  const { isTransitioning } = useRouterTransition();

  if (!isTransitioning) {
    return null;
  }

  return <div className="progress-bar" style={{ width: "100%" }} />;
}
