// examples/web/react/auth-guards/src/pages/Home.tsx
import type { JSX } from "react";

export function Home(): JSX.Element {
  return (
    <div>
      <h1>Home</h1>
      <p>
        Welcome! This example demonstrates runtime route tree replacement for
        auth.
      </p>
      <p>
        Click <strong>Login</strong> in the sidebar to authenticate.
      </p>
    </div>
  );
}

// examples/web/solid/auth-guards/src/pages/Home.tsx
import type { JSX } from "solid-js";

export function Home(): JSX.Element {
  return (
    <div>
      <h1>Home</h1>
      <p>
        Welcome! This example demonstrates runtime route tree replacement for
        auth.
      </p>
      <p>
        Click <strong>Login</strong> in the sidebar to authenticate.
      </p>
    </div>
  );
}
