// packages/router-benchmarks/client-nav/real-router/solid/app.tsx
import { useStore } from "@nanostores/solid";
import { createRouter } from "@real-router/core";
import { lifecyclePluginFactory } from "@real-router/lifecycle-plugin";
import { memoryPluginFactory } from "@real-router/memory-plugin";
import { searchSchemaPlugin } from "@real-router/search-schema-plugin";
import {
  RouterProvider,
  RouteView,
  Link,
  useRoute,
  useRouteNode,
} from "@real-router/solid";
import { atom, computed } from "nanostores";
import { createRenderEffect, For } from "solid-js";
import { render } from "solid-js/web";
import { z } from "zod";

import {
  runPerfSelectorComputation,
  normalizePage,
  noop,
} from "../../perf-utils";

import type { Route } from "@real-router/core";

const searchSchema = z.object({
  page: z.number().int().positive(),
  filter: z.string().min(1),
});

const routes: Route[] = [
  {
    name: "items",
    path: "/items/:id",
    decodeParams: (p) => ({ ...p, id: normalizePage(p.id) }),
    encodeParams: (p) => ({ ...p, id: `${p.id}` }),
    onEnter: noop,
    onStay: noop,
    onLeave: noop,
    children: [{ name: "details", path: "/details" }],
  },
  {
    name: "search",
    path: "/search?page&filter",
    defaultParams: { page: 1, filter: "all" },
    searchSchema,
  },
  {
    name: "ctx",
    path: "/ctx/:id",
    decodeParams: (p) => ({ ...p, id: normalizePage(p.id) }),
    encodeParams: (p) => ({ ...p, id: `${p.id}` }),
  },
];

const $searchParams = atom<{ page: number; filter: string }>({
  page: 1,
  filter: "all",
});

const $loaderDeps = computed($searchParams, (p) => ({
  page: p.page,
  filter: p.filter,
}));

const $loaderData = computed($loaderDeps, (d) => ({
  seed: d.page * 31 + d.filter.length,
  checksum: d.page * 17 + d.filter.length,
}));

function createAppRouter() {
  const r = createRouter(routes, {
    defaultRoute: "search",
    queryParams: { numberFormat: "auto" },
    limits: { maxListeners: 0, warnListeners: 0 },
  });

  r.usePlugin(
    memoryPluginFactory(),
    searchSchemaPlugin({ mode: "production" }),
    lifecyclePluginFactory(),
  );

  r.subscribe(({ route }) => {
    if (route.name === "search") {
      $searchParams.set({
        page: route.params.page as number,
        filter: route.params.filter as string,
      });
    }
  });

  return r;
}

const rootSelectors = Array.from({ length: 10 }, (_, i) => i);
const routeSelectors = Array.from({ length: 6 }, (_, i) => i);
const linkGroups = Array.from({ length: 4 }, (_, i) => i);

function RootParamsSubscriber(props: { index: number }) {
  const routeState = useRoute();

  createRenderEffect(() => {
    const id = Number(routeState().route?.params.id ?? 0);

    void runPerfSelectorComputation(
      runPerfSelectorComputation(id + props.index),
    );
  });

  return null;
}

function RootSearchSubscriber(props: { index: number }) {
  const routeState = useRoute();

  createRenderEffect(() => {
    const page = Number(routeState().route?.params.page ?? 0);

    void runPerfSelectorComputation(
      runPerfSelectorComputation(page + props.index),
    );
  });

  return null;
}

function ItemParamsSubscriber(props: { index: number }) {
  const routeState = useRouteNode("items");

  createRenderEffect(() => {
    const id = Number(routeState().route?.params.id ?? 0);

    void runPerfSelectorComputation(
      runPerfSelectorComputation(id + props.index),
    );
  });

  return null;
}

function SearchStateSubscriber(props: { index: number }) {
  const routeState = useRouteNode("search");

  createRenderEffect(() => {
    const page = Number(routeState().route?.params.page ?? 0);
    const filter = String(routeState().route?.params.filter ?? "");

    void runPerfSelectorComputation(
      runPerfSelectorComputation(page + filter.length + props.index),
    );
  });

  return null;
}

function SearchLoaderDepsSubscriber(props: { index: number }) {
  const deps = useStore($loaderDeps);

  createRenderEffect(() => {
    void runPerfSelectorComputation(
      runPerfSelectorComputation(
        deps().page + deps().filter.length + props.index,
      ),
    );
  });

  return null;
}

function SearchLoaderDataSubscriber(props: { index: number }) {
  const data = useStore($loaderData);

  createRenderEffect(() => {
    void runPerfSelectorComputation(
      runPerfSelectorComputation(data().seed + data().checksum + props.index),
    );
  });

  return null;
}

function ContextParamsSubscriber(props: { index: number }) {
  const routeState = useRouteNode("ctx");

  createRenderEffect(() => {
    const id = Number(routeState().route?.params.id ?? 0);

    void runPerfSelectorComputation(
      runPerfSelectorComputation(id + props.index),
    );
  });

  return null;
}

function ContextRouteSubscriber(props: { index: number }) {
  const routeState = useRouteNode("ctx");

  createRenderEffect(() => {
    const sectionSeed = Number(routeState().route?.params.id ?? 0) * 13 + 1;

    void runPerfSelectorComputation(
      runPerfSelectorComputation(sectionSeed + props.index),
    );
  });

  return null;
}

function RootSubscribers() {
  return (
    <>
      <For each={rootSelectors}>
        {(i) => <RootParamsSubscriber index={i} />}
      </For>
      <For each={rootSelectors}>
        {(i) => <RootSearchSubscriber index={i} />}
      </For>
    </>
  );
}

function LinkPanel() {
  const routeState = useRoute();

  return (
    <div data-testid="link-panel">
      <For each={linkGroups}>
        {(groupIndex) => {
          const itemsId = groupIndex === 0 ? 1 : groupIndex + 2;
          const ctxId = groupIndex + 1;

          return (
            <div>
              <Link
                routeName="items"
                routeParams={{ id: itemsId }}
                data-testid={groupIndex === 0 ? "go-items-1" : undefined}
                activeClassName="active-link"
              >
                Items {itemsId}
              </Link>
              <Link
                routeName="items"
                routeParams={{ id: 2 }}
                data-testid={groupIndex === 0 ? "go-items-2" : undefined}
                activeClassName="active-link"
              >
                Items 2 alt {groupIndex}
              </Link>
              <Link
                routeName="search"
                routeParams={{ page: 1, filter: "all" }}
                data-testid={groupIndex === 0 ? "go-search" : undefined}
                activeClassName="active-link"
              >
                Search {groupIndex}
              </Link>
              <Link
                routeName="ctx"
                routeParams={{ id: ctxId }}
                data-testid={groupIndex === 0 ? "go-ctx" : undefined}
                activeClassName="active-link"
              >
                Context {ctxId}
              </Link>
              <Link
                routeName="search"
                routeParams={{
                  page:
                    (() => {
                      const r = routeState().route;

                      return r?.name === "search"
                        ? Number(r.params.page ?? 0)
                        : 0;
                    })() +
                    groupIndex +
                    1,
                  filter: (() => {
                    const r = routeState().route;

                    return r?.name === "search"
                      ? String(r.params.filter ?? "all")
                      : "all";
                  })(),
                }}
                data-testid={groupIndex === 0 ? "search-next-page" : undefined}
                activeClassName="active-link"
              >
                Search +{groupIndex + 1}
              </Link>
            </div>
          );
        }}
      </For>
    </div>
  );
}

function ItemsPage() {
  const routeState = useRouteNode("items");

  return (
    <>
      <For each={routeSelectors}>
        {(i) => <ItemParamsSubscriber index={i} />}
      </For>
      <Link
        routeName="items.details"
        routeParams={{ id: routeState().route?.params.id }}
        data-testid="items-details"
      >
        Details
      </Link>
      <Link
        routeName="items"
        routeParams={{ id: routeState().route?.params.id }}
        data-testid="items-parent"
      >
        Parent
      </Link>
      <RouteView nodeName="items">
        <RouteView.Match segment="details">
          <ItemDetailsPage />
        </RouteView.Match>
      </RouteView>
    </>
  );
}

function ItemDetailsPage() {
  return (
    <For each={routeSelectors}>{(i) => <ItemParamsSubscriber index={i} />}</For>
  );
}

function SearchPage() {
  return (
    <>
      <For each={routeSelectors}>
        {(i) => <SearchStateSubscriber index={i} />}
      </For>
      <For each={routeSelectors}>
        {(i) => <SearchLoaderDepsSubscriber index={i} />}
      </For>
      <For each={routeSelectors}>
        {(i) => <SearchLoaderDataSubscriber index={i} />}
      </For>
    </>
  );
}

function ContextPage() {
  return (
    <>
      <For each={routeSelectors}>
        {(i) => <ContextParamsSubscriber index={i} />}
      </For>
      <For each={routeSelectors}>
        {(i) => <ContextRouteSubscriber index={i} />}
      </For>
    </>
  );
}

function App(props: { appRouter: ReturnType<typeof createAppRouter> }) {
  return (
    <RouterProvider router={props.appRouter}>
      <RootSubscribers />
      <LinkPanel />
      <RouteView nodeName="">
        <RouteView.Match segment="items">
          <ItemsPage />
        </RouteView.Match>
        <RouteView.Match segment="search">
          <SearchPage />
        </RouteView.Match>
        <RouteView.Match segment="ctx">
          <ContextPage />
        </RouteView.Match>
      </RouteView>
    </RouterProvider>
  );
}

export function mountTestApp(container: HTMLElement) {
  const router = createAppRouter();
  const dispose = render(() => <App appRouter={router} />, container);

  return {
    router,
    unmount() {
      dispose();
      router.stop();
    },
  };
}

// packages/router-benchmarks/client-nav/tanstack/vue/app.tsx
import {
  Link,
  Outlet,
  RouterProvider,
  createMemoryHistory,
  createRootRoute,
  createRoute,
  createRouter,
  useParams,
  useSearch,
} from "@tanstack/vue-router";
import * as Vue from "vue";

function runPerfSelectorComputation(seed: number) {
  let value = Math.trunc(seed) | 0;

  for (let index = 0; index < 40; index++) {
    value = (value * 1_664_525 + 1_013_904_223 + index) >>> 0;
  }

  return value;
}

function normalizePage(value: unknown) {
  const page = Number(value);

  return Number.isFinite(page) && page > 0 ? Math.trunc(page) : 1;
}

function normalizeFilter(value: unknown) {
  return typeof value === "string" && value.length > 0 ? value : "all";
}

const noop = () => {};
const rootSelectors = Array.from({ length: 10 }, (_, index) => index);
const routeSelectors = Array.from({ length: 6 }, (_, index) => index);
const linkGroups = Array.from({ length: 4 }, (_, index) => index);

const RootParamsSubscriber = Vue.defineComponent({
  setup() {
    const params = useParams({
      strict: false,
      select: (params) => runPerfSelectorComputation(Number(params.id ?? 0)),
    });

    return () => {
      void runPerfSelectorComputation(params.value);

      return null;
    };
  },
});

const RootSearchSubscriber = Vue.defineComponent({
  setup() {
    const search = useSearch({
      strict: false,
      select: (search) => runPerfSelectorComputation(Number(search.page ?? 0)),
    });

    return () => {
      void runPerfSelectorComputation(search.value);

      return null;
    };
  },
});

const LinkPanel = Vue.defineComponent({
  setup() {
    return () => (
      <>
        {linkGroups.map((groupIndex) => {
          const itemsId = groupIndex === 0 ? 1 : groupIndex + 2;
          const ctxId = groupIndex + 1;

          return (
            <div key={groupIndex}>
              <Link
                data-testid={groupIndex === 0 ? "go-items-1" : undefined}
                to="/items/$id"
                params={{ id: itemsId }}
                replace
                activeOptions={{ exact: true }}
                activeProps={{ class: "active-link" }}
                inactiveProps={{ class: "inactive-link" }}
              >
                {`Items ${itemsId}`}
              </Link>
              <Link
                data-testid={groupIndex === 0 ? "go-items-2" : undefined}
                to="/items/$id"
                params={{ id: 2 }}
                replace
                activeOptions={{ includeSearch: false }}
              >
                {`Items 2 alt ${groupIndex}`}
              </Link>
              <Link
                data-testid={groupIndex === 0 ? "go-search" : undefined}
                to="/search"
                search={{ page: 1, filter: "all", junk: `group-${groupIndex}` }}
                replace
                activeOptions={{ includeSearch: true }}
                activeProps={{ class: "active-link" }}
                inactiveProps={{ class: "inactive-link" }}
              >
                {`Search ${groupIndex}`}
              </Link>
              <Link
                data-testid={groupIndex === 0 ? "go-ctx" : undefined}
                to="/ctx/$id"
                params={{ id: ctxId }}
                search={true}
                replace
                activeOptions={{ includeSearch: false }}
              >
                {`Context ${ctxId}`}
              </Link>
              <Link
                from={searchRoute.fullPath}
                to="/search"
                search={(prev: { page: number; filter: string }) => ({
                  page: prev.page + groupIndex + 1,
                  filter: prev.filter,
                  junk: `updater-${groupIndex}`,
                })}
                activeOptions={{ includeSearch: true }}
              >
                {({ isActive }: { isActive: boolean }) =>
                  isActive
                    ? `Search updater active ${groupIndex}`
                    : `Search updater inactive ${groupIndex}`
                }
              </Link>
            </div>
          );
        })}
      </>
    );
  },
});

const Root = Vue.defineComponent({
  setup() {
    return () => (
      <>
        {rootSelectors.map((selector) => (
          <RootParamsSubscriber key={`root-params-${selector}`} />
        ))}
        {rootSelectors.map((selector) => (
          <RootSearchSubscriber key={`root-search-${selector}`} />
        ))}
        <LinkPanel />
        <Outlet />
      </>
    );
  },
});

const rootRoute = createRootRoute({
  component: Root,
});

const ItemParamsSubscriber = Vue.defineComponent({
  setup() {
    const params = itemsRoute.useParams({
      select: (params) => runPerfSelectorComputation(params.id),
    });

    return () => {
      void runPerfSelectorComputation(params.value);

      return null;
    };
  },
});

const SearchStateSubscriber = Vue.defineComponent({
  setup() {
    const search = searchRoute.useSearch({
      select: (search) =>
        runPerfSelectorComputation(search.page + search.filter.length),
    });

    return () => {
      void runPerfSelectorComputation(search.value);

      return null;
    };
  },
});

const SearchLoaderDepsSubscriber = Vue.defineComponent({
  setup() {
    const loaderDeps = searchRoute.useLoaderDeps({
      select: (loaderDeps) =>
        runPerfSelectorComputation(loaderDeps.page + loaderDeps.filter.length),
    });

    return () => {
      void runPerfSelectorComputation(loaderDeps.value);

      return null;
    };
  },
});

const SearchLoaderDataSubscriber = Vue.defineComponent({
  setup() {
    const loaderData = searchRoute.useLoaderData({
      select: (loaderData) =>
        runPerfSelectorComputation(loaderData.seed + loaderData.checksum),
    });

    return () => {
      void runPerfSelectorComputation(loaderData.value);

      return null;
    };
  },
});

const ContextParamsSubscriber = Vue.defineComponent({
  setup() {
    const params = contextRoute.useParams({
      select: (params) => runPerfSelectorComputation(Number(params.id)),
    });

    return () => {
      void runPerfSelectorComputation(params.value);

      return null;
    };
  },
});

const ContextRouteSubscriber = Vue.defineComponent({
  setup() {
    const context = contextRoute.useRouteContext({
      select: (context) => runPerfSelectorComputation(context.sectionSeed),
    });

    return () => {
      void runPerfSelectorComputation(context.value);

      return null;
    };
  },
});

const ItemsPage = Vue.defineComponent({
  setup() {
    return () => (
      <>
        {routeSelectors.map((selector) => (
          <ItemParamsSubscriber key={`item-params-${selector}`} />
        ))}
        <Link
          data-testid="items-details"
          from={itemsRoute.fullPath}
          to="./details"
          replace
        >
          Details
        </Link>
        <Link
          from={itemsRoute.fullPath}
          to="."
          search={true}
          activeOptions={{ includeSearch: true }}
        >
          Preserve search on item
        </Link>
        <Outlet />
      </>
    );
  },
});

const ItemDetailsPage = Vue.defineComponent({
  setup() {
    return () => (
      <>
        {routeSelectors.map((selector) => (
          <ItemParamsSubscriber key={`detail-params-${selector}`} />
        ))}
        <Link
          data-testid="items-parent"
          from={itemDetailsRoute.fullPath}
          to=".."
          replace
          activeOptions={{ exact: true }}
        >
          Back to item
        </Link>
      </>
    );
  },
});

const SearchPage = Vue.defineComponent({
  setup() {
    return () => (
      <>
        {routeSelectors.map((selector) => (
          <SearchStateSubscriber key={`search-state-${selector}`} />
        ))}
        {routeSelectors.map((selector) => (
          <SearchLoaderDepsSubscriber key={`search-loader-deps-${selector}`} />
        ))}
        {routeSelectors.map((selector) => (
          <SearchLoaderDataSubscriber key={`search-loader-data-${selector}`} />
        ))}
        <Link
          data-testid="search-next-page"
          from={searchRoute.fullPath}
          to="."
          replace
          search={(prev: { page: number; filter: string }) => ({
            page: prev.page + 1,
            filter: prev.filter,
            junk: "local-updater",
          })}
          activeOptions={{ includeSearch: true }}
          activeProps={{ class: "active-link" }}
          inactiveProps={{ class: "inactive-link" }}
        >
          Next page
        </Link>
      </>
    );
  },
});

const ContextPage = Vue.defineComponent({
  setup() {
    return () => (
      <>
        {routeSelectors.map((selector) => (
          <ContextParamsSubscriber key={`context-params-${selector}`} />
        ))}
        {routeSelectors.map((selector) => (
          <ContextRouteSubscriber key={`context-route-${selector}`} />
        ))}
      </>
    );
  },
});

const itemsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/items/$id",
  params: {
    parse: (params) => ({
      ...params,
      id: normalizePage(params.id),
    }),
    stringify: (params) => ({
      ...params,
      id: `${params.id}`,
    }),
  },
  onEnter: noop,
  onStay: noop,
  onLeave: noop,
  component: ItemsPage,
});

const itemDetailsRoute = createRoute({
  getParentRoute: () => itemsRoute,
  path: "details",
  component: ItemDetailsPage,
});

const searchRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/search",
  validateSearch: (search: Record<string, unknown>) => ({
    page: normalizePage(search.page),
    filter: normalizeFilter(search.filter),
  }),
  search: {
    middlewares: [
      ({ search, next }) => {
        const result = next(search);

        return {
          page: result.page,
          filter: result.filter,
        };
      },
    ],
  },
  loaderDeps: ({ search }) => ({
    page: search.page,
    filter: search.filter,
  }),
  loader: ({ deps }) => ({
    seed: deps.page * 31 + deps.filter.length,
    checksum: deps.page * 17 + deps.filter.length,
  }),
  staleTime: 60_000,
  gcTime: 60_000,
  component: SearchPage,
});

const contextRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/ctx/$id",
  beforeLoad: ({ params }) => ({
    sectionSeed: Number(params.id) * 13 + 1,
  }),
  component: ContextPage,
});

export function mountTestApp(container: Element) {
  const router = createRouter({
    history: createMemoryHistory({
      initialEntries: ["/items/0"],
    }),
    scrollRestoration: true,
    routeTree: rootRoute.addChildren([
      itemsRoute.addChildren([itemDetailsRoute]),
      searchRoute,
      contextRoute,
    ]),
  });

  const component = <RouterProvider router={router} />;
  const app = Vue.createApp({
    render: () => component,
  });

  app.mount(container);

  return {
    router,
    unmount() {
      app.unmount();
    },
  };
}
