// examples/web/angular/ssr-examples/ssr-mixed/src/pages/home.component.ts
import { Component, computed } from "@angular/core";
import { injectRoute, injectRouter } from "@real-router/angular";
import { invalidate } from "@real-router/ssr-data-plugin";

interface HomeData {
  greeting: string;
  fetchedAt: number;
  aborts: number;
}

@Component({
  selector: "home-page",
  template: `
    <main data-testid="home">
      <h1>Home (full SSR)</h1>
      <p data-testid="greeting">{{ data()?.greeting ?? "(no data)" }}</p>
      @if (data()?.fetchedAt !== undefined) {
        <p data-testid="fetched-at">{{ data()?.fetchedAt }}</p>
      }
      @if (data()?.aborts !== undefined) {
        <p data-testid="aborts">{{ data()?.aborts }}</p>
      }
      <button
        type="button"
        data-testid="refresh-btn"
        (click)="onRefresh()"
      >
        Refresh data
      </button>
    </main>
  `,
})
export class HomeComponent {
  private readonly route = injectRoute();
  private readonly router = injectRouter();

  readonly data = computed<HomeData | undefined>(
    () => this.route.routeState().route.context.data as HomeData | undefined,
  );

  // Escape hatch: mark "data" stale, then trigger a same-route reload.
  // Reload bypasses stabilizeState dedupe (#605), so injectRoute() re-emits
  // the fresh snapshot written by the plugin's subscribeLeave handler.
  onRefresh(): void {
    const current = this.route.routeState().route;

    invalidate(this.router, "data");
    void this.router.navigate(
      current.name,
      current.params,
      undefined,
      { reload: true },
    );
  }
}

// examples/web/svelte/ssr-examples/ssr-mixed/src/pages/Home.svelte
<script lang="ts">
  import { useRoute, useRouter } from "@real-router/svelte";
  import { invalidate } from "@real-router/ssr-data-plugin";

  interface HomeData {
    greeting: string;
    fetchedAt: number;
    aborts: number;
  }

  const { route } = useRoute();
  const router = useRouter();
  const data = $derived(route.current.context.data as HomeData | undefined);

  // Escape hatch: mark "data" stale, then trigger a same-route reload.
  // Reload bypasses stabilizeState dedupe (#605), so useRoute() re-emits
  // the fresh snapshot written by the plugin's subscribeLeave handler.
  function handleRefresh(): void {
    const current = route.current;

    invalidate(router, "data");
    void router.navigate(current.name, current.params, { reload: true });
  }
</script>

<main data-testid="home">
  <h1>Home (full SSR)</h1>
  <p data-testid="greeting">{data?.greeting ?? "(no data)"}</p>
  {#if data?.fetchedAt !== undefined}
    <p data-testid="fetched-at">{data.fetchedAt}</p>
  {/if}
  {#if data?.aborts !== undefined}
    <p data-testid="aborts">{data.aborts}</p>
  {/if}
  <button type="button" data-testid="refresh-btn" onclick={handleRefresh}>
    Refresh data
  </button>
</main>
