// examples/solid/basic/src/pages/About.tsx
import type { JSX } from "solid-js";

export function About(): JSX.Element {
  return (
    <div>
      <h1>About</h1>
      <p>This is the about page of the Real-Router basic example.</p>
      <p>
        Real-Router is a data-first router for JavaScript — URLs map to state,
        not components. The router tells you <em>where</em> the user is; you
        decide what to render.
      </p>
    </div>
  );
}

// examples/web/react/basic/src/pages/About.tsx
import type { JSX } from "react";

export function About(): JSX.Element {
  return (
    <div>
      <h1>About</h1>
      <p>This is the about page of the Real-Router basic example.</p>
      <p>
        Real-Router is a data-first router for JavaScript — URLs map to state,
        not components. The router tells you <em>where</em> the user is; you
        decide what to render.
      </p>
    </div>
  );
}
