// examples/web/solid/use-link-directive/src/pages/ProductDetail.tsx
import { link, useRouteNode } from "@real-router/solid";

import type { JSX } from "solid-js";

// Keep reference to prevent tree-shaking (Solid directive pattern)
link;

export function ProductDetail(): JSX.Element {
  const nodeState = useRouteNode("products.detail");

  const id = () => {
    const route = nodeState().route;

    return route && typeof route.params.id === "string" ? route.params.id : "?";
  };

  return (
    <div>
      <h1>Product #{id()}</h1>
      <div class="card">
        <p>Product detail page for item {id()}.</p>
        <p>
          You navigated here via <code>use:link</code> directive on a{" "}
          <code>&lt;div&gt;</code> card.
        </p>
      </div>
      <a use:link={() => ({ routeName: "home" })}>← Back to Home</a>
    </div>
  );
}

// examples/web/svelte/link-action/src/pages/ProductDetail.svelte
<script lang="ts">
  import { useRouteNode, createLinkAction } from "@real-router/svelte";

  const { route } = useRouteNode("products.detail");
  const link = createLinkAction();

  const id = $derived(
    route.current && typeof route.current.params.id === "string"
      ? route.current.params.id
      : "?"
  );
</script>

<div>
  <h1>Product #{id}</h1>
  <div class="card">
    <p>Product detail page — navigated here via <code>use:link</code> action on a card div.</p>
    <p>The action adds <code>role="link"</code> and <code>tabindex="0"</code> for accessibility.</p>
  </div>
  <button use:link={{ name: "home" }}>← Back to Home (use:link on button)</button>
</div>
