// benchmarks/vs-tanstack/unique-location-churn/tanstack/solid/app.tsx
import {
  Outlet,
  RouterProvider,
  createMemoryHistory,
  createRootRoute,
  createRoute,
  createRouter,
} from "@tanstack/solid-router";
import { render } from "solid-js/web";

const rootRoute = createRootRoute({ component: () => <Outlet /> });

const itemsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/items/$id",
  validateSearch: (search: Record<string, unknown>) => ({
    q: typeof search.q === "string" ? search.q : "",
  }),
  loaderDeps: ({ search }) => ({ q: search.q }),
  loader: ({ params, deps }) => ({ id: params.id, q: deps.q }),
  component: ItemComponent,
});

function ItemComponent() {
  const data = itemsRoute.useLoaderData();

  return <main data-bench-id={data().id}>{`${data().id}:${data().q}`}</main>;
}

export function mountTestApp(container: Element) {
  const router = createRouter({
    history: createMemoryHistory({ initialEntries: ["/items/0?q="] }),
    routeTree: rootRoute.addChildren([itemsRoute]),
  });

  const unmount = render(() => <RouterProvider router={router} />, container);

  return {
    router,
    unmount,
  };
}

// benchmarks/vs-tanstack/mount-unmount/tanstack/react/app.tsx
import {
  Outlet,
  RouterProvider,
  createMemoryHistory,
  createRootRoute,
  createRoute,
  createRouter,
} from "@tanstack/react-router";
import { createRoot } from "react-dom/client";

const rootRoute = createRootRoute({ component: () => <Outlet /> });

const aRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/a",
  component: () => <main data-bench-page="a">A</main>,
});

export function mountTestApp(container: Element) {
  const router = createRouter({
    history: createMemoryHistory({ initialEntries: ["/a"] }),
    routeTree: rootRoute.addChildren([aRoute]),
  });
  const reactRoot = createRoot(container);
  let didUnmount = false;

  reactRoot.render(<RouterProvider router={router} />);

  // Full teardown: guard double-unmount and detach history listeners.
  return {
    router,
    unmount() {
      if (didUnmount) {
        return;
      }

      didUnmount = true;
      reactRoot.unmount();
      router.history.destroy();
    },
  };
}
