// packages/react/src/RouterProvider.tsx
import { getNavigator } from "@real-router/core";
import { createRouteSource } from "@real-router/sources";
import { useEffect, useMemo, useSyncExternalStore } from "react";

import { NavigatorContext, RouteContext, RouterContext } from "./context";
import {
  createRouteAnnouncer,
  createScrollRestoration,
  createViewTransitions,
} from "./dom-utils";

import type { ScrollRestorationOptions } from "./dom-utils";
import type { Router } from "@real-router/core";
import type { FC, ReactNode } from "react";

export interface RouteProviderProps {
  router: Router;
  children: ReactNode;
  announceNavigation?: boolean;
  scrollRestoration?: ScrollRestorationOptions;
  viewTransitions?: boolean;
}

export const RouterProvider: FC<RouteProviderProps> = ({
  router,
  children,
  announceNavigation,
  scrollRestoration,
  viewTransitions,
}) => {
  useEffect(() => {
    if (!announceNavigation) {
      return;
    }

    const announcer = createRouteAnnouncer(router);

    return () => {
      announcer.destroy();
    };
  }, [announceNavigation, router]);

  // Primitive deps so inline `{ mode: "restore" }` doesn't thrash on every
  // render. scrollContainer is a getter invoked lazily on every event inside
  // the utility — swapping its reference doesn't change the resolved element,
  // so we intentionally omit it from deps to keep inline getters stable.
  const srMode = scrollRestoration?.mode;
  const srAnchor = scrollRestoration?.anchorScrolling;
  const srBehavior = scrollRestoration?.behavior;
  const srStorageKey = scrollRestoration?.storageKey;
  const srEnabled = scrollRestoration !== undefined;

  useEffect(() => {
    if (!srEnabled) {
      return;
    }

    const sr = createScrollRestoration(router, {
      mode: srMode,
      anchorScrolling: srAnchor,
      behavior: srBehavior,
      storageKey: srStorageKey,
      // srEnabled check above guarantees scrollRestoration is defined.
      scrollContainer: scrollRestoration.scrollContainer,
    });

    return () => {
      sr.destroy();
    };
    // scrollRestoration (for scrollContainer) omitted — see comment above.
    // eslint-disable-next-line @eslint-react/exhaustive-deps
  }, [router, srEnabled, srMode, srAnchor, srBehavior, srStorageKey]);

  useEffect(() => {
    if (!viewTransitions) {
      return;
    }

    const vt = createViewTransitions(router);

    return () => {
      vt.destroy();
    };
  }, [router, viewTransitions]);

  const navigator = useMemo(() => getNavigator(router), [router]);

  // useSyncExternalStore manages the router subscription lifecycle:
  // subscribe connects to router on first listener, unsubscribes on last.
  // This is Strict Mode safe — no useEffect cleanup needed.
  const store = useMemo(() => createRouteSource(router), [router]);
  // Use snapshot reference directly. createRouteSource via stabilizeState
  // returns the SAME snapshot reference when route.path is unchanged, so
  // useMemo below sees stable deps for idempotent navigations and
  // RouteContext consumers do not re-render.
  const snapshot = useSyncExternalStore(
    store.subscribe,
    store.getSnapshot,
    store.getSnapshot, // SSR: router returns same state on server and client
  );

  const routeContextValue = useMemo(
    () => ({
      navigator,
      route: snapshot.route,
      previousRoute: snapshot.previousRoute,
    }),
    [navigator, snapshot],
  );

  return (
    <RouterContext.Provider value={router}>
      <NavigatorContext.Provider value={navigator}>
        <RouteContext.Provider value={routeContextValue}>
          {children}
        </RouteContext.Provider>
      </NavigatorContext.Provider>
    </RouterContext.Provider>
  );
};

// packages/svelte/src/RouterProvider.svelte
<script lang="ts">
  import { getNavigator } from "@real-router/core";
  import { createRouteSource } from "@real-router/sources";
  import {
    createRouteAnnouncer,
    createScrollRestoration,
    createViewTransitions,
  } from "./dom-utils";
  import { setContext, untrack } from "svelte";

  import { createReactiveSource } from "./createReactiveSource.svelte";
  import { createRouteContext } from "./createRouteContext.svelte";
  import { NAVIGATOR_KEY, ROUTE_KEY, ROUTER_KEY } from "./context";

  import type { ScrollRestorationOptions } from "./dom-utils";
  import type { Router } from "@real-router/core";
  import type { Snippet } from "svelte";

  let {
    router,
    children,
    announceNavigation,
    scrollRestoration,
    viewTransitions,
  }: {
    router: Router;
    children: Snippet;
    announceNavigation?: boolean;
    scrollRestoration?: ScrollRestorationOptions;
    viewTransitions?: boolean;
  } = $props();

  $effect(() => {
    if (!announceNavigation) return;
    const announcer = createRouteAnnouncer(router);
    return () => announcer.destroy();
  });

  // $derived memoizes by === so inline `{ mode: "restore" }` doesn't thrash:
  // each parent re-render produces a new object ref, but .mode stays "restore"
  // → $derived returns the same primitive → $effect doesn't re-run.
  const srEnabled = $derived(scrollRestoration !== undefined);
  const srMode = $derived(scrollRestoration?.mode);
  const srAnchor = $derived(scrollRestoration?.anchorScrolling);
  const srBehavior = $derived(scrollRestoration?.behavior);
  const srStorageKey = $derived(scrollRestoration?.storageKey);

  $effect(() => {
    if (!srEnabled) return;
    // Read scrollRestoration object props via `untrack` for non-primitive
    // refs that naturally change each render. Primitive $derived memos
    // (mode/anchor/behavior/storageKey) drive re-runs.
    void srMode;
    void srAnchor;
    void srBehavior;
    void srStorageKey;
    const sr = createScrollRestoration(router, {
      mode: srMode,
      anchorScrolling: srAnchor,
      behavior: srBehavior,
      storageKey: srStorageKey,
      scrollContainer: untrack(() => scrollRestoration?.scrollContainer),
    });
    return () => sr.destroy();
  });

  $effect(() => {
    if (!viewTransitions) return;
    const vt = createViewTransitions(router);
    return () => vt.destroy();
  });

  const navigator = getNavigator(router);
  const source = createRouteSource(router);
  const reactive = createReactiveSource(source);
  const routeContext = createRouteContext(navigator, reactive);

  setContext(ROUTER_KEY, router);
  setContext(NAVIGATOR_KEY, navigator);
  setContext(ROUTE_KEY, routeContext);
</script>

{@render children()}
