// packages/solid/src/components/RouteView/helpers.tsx
import { UNKNOWN_ROUTE } from "@real-router/core";
import { startsWithSegment } from "@real-router/route-utils";
import { Suspense } from "solid-js";

import { MATCH_MARKER, NOT_FOUND_MARKER } from "./components";

import type {
  MatchMarker,
  NotFoundMarker,
  RouteViewMarker,
} from "./components";
import type { JSX } from "solid-js";

export function isSegmentMatch(
  routeName: string,
  fullSegmentName: string,
  exact: boolean,
): boolean {
  if (exact) {
    return routeName === fullSegmentName;
  }

  return startsWithSegment(routeName, fullSegmentName);
}

function isMatchMarker(value: unknown): value is MatchMarker {
  return (
    value != null &&
    typeof value === "object" &&
    "$$type" in value &&
    value.$$type === MATCH_MARKER
  );
}

function isNotFoundMarker(value: unknown): value is NotFoundMarker {
  return (
    value != null &&
    typeof value === "object" &&
    "$$type" in value &&
    value.$$type === NOT_FOUND_MARKER
  );
}

export function collectElements(
  children: unknown,
  result: RouteViewMarker[],
): void {
  if (children == null) {
    return;
  }

  if (Array.isArray(children)) {
    for (const child of children) {
      collectElements(child, result);
    }

    return;
  }

  if (isMatchMarker(children) || isNotFoundMarker(children)) {
    result.push(children);
  }
}

export function buildRenderList(
  elements: RouteViewMarker[],
  routeName: string,
  nodeName: string,
): JSX.Element[] {
  let notFoundChildren: JSX.Element | null = null;
  let activeMatchFound = false;
  const rendered: JSX.Element[] = [];

  for (const child of elements) {
    if (isNotFoundMarker(child)) {
      notFoundChildren = child.children;
      continue;
    }

    if (activeMatchFound) {
      continue;
    }

    const { segment, exact, fallback } = child;
    const fullSegmentName = nodeName ? `${nodeName}.${segment}` : segment;

    if (!isSegmentMatch(routeName, fullSegmentName, exact)) {
      continue;
    }

    activeMatchFound = true;
    rendered.push(
      fallback === undefined ? (
        child.children
      ) : (
        <Suspense fallback={fallback}>{child.children}</Suspense>
      ),
    );
  }

  if (
    !activeMatchFound &&
    routeName === UNKNOWN_ROUTE &&
    notFoundChildren !== null
  ) {
    rendered.push(notFoundChildren);
  }

  return rendered;
}

// packages/react/src/components/modern/RouteView/helpers.tsx
import { UNKNOWN_ROUTE } from "@real-router/core";
import { startsWithSegment } from "@real-router/route-utils";
import { Activity, Children, Fragment, Suspense, isValidElement } from "react";

import { Match, NotFound } from "./components";

import type { MatchProps, NotFoundProps } from "./types";
import type { ReactElement, ReactNode } from "react";

function isSegmentMatch(
  routeName: string,
  fullSegmentName: string,
  exact: boolean,
): boolean {
  if (fullSegmentName === "") {
    return false;
  }

  if (exact) {
    return routeName === fullSegmentName;
  }

  return startsWithSegment(routeName, fullSegmentName);
}

export function collectElements(
  children: ReactNode,
  result: ReactElement[],
): void {
  // eslint-disable-next-line @eslint-react/no-children-to-array
  for (const child of Children.toArray(children)) {
    if (!isValidElement(child)) {
      continue;
    }

    if (child.type === Match || child.type === NotFound) {
      result.push(child);
    } else {
      collectElements(
        (child.props as { readonly children: ReactNode }).children,
        result,
      );
    }
  }
}

function renderMatchElement(
  matchChildren: ReactNode,
  fullSegmentName: string,
  keepAlive: boolean,
  mode: "visible" | "hidden",
  fallback?: ReactNode,
): ReactElement {
  const content =
    fallback === undefined ? (
      matchChildren
    ) : (
      <Suspense fallback={fallback}>{matchChildren}</Suspense>
    );

  if (keepAlive) {
    return (
      <Activity mode={mode} key={fullSegmentName}>
        {content}
      </Activity>
    );
  }

  return <Fragment key={fullSegmentName}>{content}</Fragment>;
}

export function buildRenderList(
  elements: ReactElement[],
  routeName: string,
  nodeName: string,
  hasBeenActivated: Set<string>,
): { rendered: ReactElement[]; activeMatchFound: boolean } {
  let notFoundChildren: ReactNode = null;
  let activeMatchFound = false;
  const rendered: ReactElement[] = [];

  for (const child of elements) {
    if (child.type === NotFound) {
      notFoundChildren = (child.props as NotFoundProps).children;
      continue;
    }

    const {
      segment,
      exact = false,
      keepAlive = false,
      fallback,
    } = child.props as MatchProps;
    const fullSegmentName = nodeName ? `${nodeName}.${segment}` : segment;
    const isActive =
      !activeMatchFound && isSegmentMatch(routeName, fullSegmentName, exact);

    if (isActive) {
      activeMatchFound = true;
      hasBeenActivated.add(fullSegmentName);
      rendered.push(
        renderMatchElement(
          (child.props as MatchProps).children,
          fullSegmentName,
          keepAlive,
          "visible",
          fallback,
        ),
      );
    } else if (keepAlive && hasBeenActivated.has(fullSegmentName)) {
      rendered.push(
        renderMatchElement(
          (child.props as MatchProps).children,
          fullSegmentName,
          keepAlive,
          "hidden",
          fallback,
        ),
      );
    }
  }

  if (
    !activeMatchFound &&
    routeName === UNKNOWN_ROUTE &&
    notFoundChildren !== null
  ) {
    rendered.push(
      <Fragment key="__route-view-not-found__">{notFoundChildren}</Fragment>,
    );
  }

  return { rendered, activeMatchFound };
}
