// examples/web/preact/combined/src/pages/Settings.tsx
import { useEffect, useState } from "preact/hooks";

import { store } from "../../../../../shared/store";

import type { JSX } from "preact";

export function Settings(): JSX.Element {
  const [displayName, setDisplayName] = useState("");

  useEffect(() => {
    store.set("settings:unsaved", displayName !== "");

    return () => {
      store.set("settings:unsaved", false);
    };
  }, [displayName]);

  return (
    <div>
      <h1>Settings</h1>
      <div className="card">
        <div className="form-group">
          <label>Display Name</label>
          <input
            value={displayName}
            onChange={(event) => {
              setDisplayName((event.target as HTMLInputElement).value);
            }}
            placeholder="Enter your display name…"
          />
        </div>
        {displayName && (
          <p style={{ color: "#c62828", fontSize: "14px" }}>
            Unsaved changes — navigating away triggers{" "}
            <code>canDeactivate</code>.
          </p>
        )}
        <button className="primary" style={{ marginTop: "8px" }}>
          Save
        </button>
      </div>
    </div>
  );
}

// examples/web/vue/combined/src/pages/Settings.vue
<script setup lang="ts">
import { onUnmounted, ref, watch } from "vue";
import { store } from "../../../../shared/store";

const displayName = ref("");

watch(displayName, (val) => {
  store.set("settings:unsaved", val !== "");
});

onUnmounted(() => {
  store.set("settings:unsaved", false);
});
</script>

<template>
  <div>
    <h1>Settings</h1>
    <div class="card">
      <div class="form-group">
        <label>Display Name</label>
        <input v-model="displayName" placeholder="Enter your display name…" />
      </div>
      <p v-if="displayName" :style="{ color: '#c62828', fontSize: '14px' }">
        Unsaved changes — navigating away triggers <code>canDeactivate</code>.
      </p>
      <button class="primary" :style="{ marginTop: '8px' }">Save</button>
    </div>
  </div>
</template>
