// examples/web/vue/keep-alive/src/pages/Reports.vue
<script setup lang="ts">
import { useNavigator } from "@real-router/vue";
import { onMounted, ref, watchEffect } from "vue";

const navigator = useNavigator();
const scrollContainerRef = ref<Element | null>(null);

onMounted(() => {
  const saved = sessionStorage.getItem("reports:scrollY");

  if (saved && scrollContainerRef.value) {
    requestAnimationFrame(() => {
      scrollContainerRef.value?.scrollTo(0, Number(saved));
    });
  }
});

watchEffect((onCleanup) => {
  const unsub = navigator.subscribeLeave(({ route }) => {
    if (route.name === "reports" && scrollContainerRef.value) {
      sessionStorage.setItem(
        "reports:scrollY",
        String(scrollContainerRef.value.scrollTop),
      );
    }
  });

  onCleanup(unsub);
});
</script>

<template>
  <div>
    <h1>Reports</h1>
    <p style="color: #666; font-size: 14px">
      Scroll position preserved via <code>subscribeLeave()</code> — no KeepAlive
      needed.
    </p>
    <div
      ref="scrollContainerRef"
      class="reports-scroll-container"
      style="height: 400px; overflow-y: auto; border: 1px solid #ddd"
    >
      <div
        v-for="i in 50"
        :key="i"
        style="padding: 12px 16px; border-bottom: 1px solid #eee"
      >
        Report item #{{ i }} — Q{{ ((i - 1) % 4) + 1 }} 2024
      </div>
    </div>
  </div>
</template>

// examples/react/keepAlive/src/pages/Reports.tsx
import { useEffect, useRef } from "react";
import { useNavigator } from "@real-router/react";

import type { JSX } from "react";

export function Reports(): JSX.Element {
  const navigator = useNavigator();
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const saved = sessionStorage.getItem("reports:scrollY");

    if (saved && containerRef.current) {
      requestAnimationFrame(() => {
        if (containerRef.current) {
          containerRef.current.scrollTop = Number(saved);
        }
      });
    }

    return navigator.subscribeLeave(({ route }) => {
      if (route.name === "reports" && containerRef.current) {
        sessionStorage.setItem(
          "reports:scrollY",
          String(containerRef.current.scrollTop),
        );
      }
    });
  }, [navigator]);

  return (
    <div>
      <h1>Reports</h1>
      <p>
        Scroll position preserved via <code>subscribeLeave()</code> — no
        keepAlive needed.
      </p>
      <div
        ref={containerRef}
        className="reports-scroll-container"
        style={{ height: "400px", overflowY: "auto", border: "1px solid #ddd" }}
      >
        {Array.from({ length: 50 }, (_, i) => (
          <div
            key={i}
            style={{ padding: "12px 16px", borderBottom: "1px solid #eee" }}
          >
            Report item #{i + 1} — Q{(i % 4) + 1} 2024
          </div>
        ))}
      </div>
    </div>
  );
}
