// examples/web/vue/auth-guards/src/pages/Login.vue
<script setup lang="ts">
import { ref } from "vue";
import { api } from "../../../../../shared/api";

import type { User } from "../../../../../shared/api";

const emit = defineEmits<{
  login: [user: User];
}>();

const email = ref("");
const password = ref("");
const error = ref<string | null>(null);
const loading = ref(false);

async function handleSubmit() {
  error.value = null;
  loading.value = true;
  try {
    const user = await api.login(email.value, password.value);

    if (!user) {
      error.value =
        "Invalid credentials. Try alice@example.com or bob@example.com";

      return;
    }

    emit("login", user);
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div>
    <h1>Login</h1>
    <form @submit.prevent="handleSubmit()">
      <div class="form-group">
        <label>Email</label>
        <input
          type="email"
          v-model="email"
          placeholder="alice@example.com"
          required
        />
      </div>
      <div class="form-group">
        <label>Password</label>
        <input
          type="password"
          v-model="password"
          placeholder="any password"
          required
        />
      </div>
      <div v-if="error" class="toast error">{{ error }}</div>
      <button type="submit" class="primary" :disabled="loading">
        {{ loading ? "Logging in…" : "Login" }}
      </button>
    </form>
    <div class="card" :style="{ marginTop: '16px' }">
      <p><strong>Try these accounts:</strong></p>
      <p>alice@example.com — Admin (access to all routes)</p>
      <p>bob@example.com — Editor (no Admin page)</p>
      <p>carol@example.com — Viewer (no Admin page)</p>
      <p>Any password works in this demo.</p>
    </div>
  </div>
</template>

// examples/svelte/auth-guards/src/pages/Login.svelte
<script lang="ts">
  import { api } from "../../../../shared/api";

  import type { User } from "../../../../shared/api";

  let { onLogin }: { onLogin: (user: User) => Promise<void> } = $props();

  let email = $state("");
  let password = $state("");
  let error = $state<string | null>(null);
  let loading = $state(false);

  const handleSubmit = async (event: { preventDefault: () => void }) => {
    event.preventDefault();
    error = null;
    loading = true;
    try {
      const user = await api.login(email, password);

      if (!user) {
        error =
          "Invalid credentials. Try alice@example.com or bob@example.com";

        return;
      }

      await onLogin(user);
    } finally {
      loading = false;
    }
  };
</script>

<div>
  <h1>Login</h1>
  <form onsubmit={(event) => void handleSubmit(event)}>
    <div class="form-group">
      <label>Email</label>
      <input
        type="email"
        value={email}
        oninput={(event) => { email = event.currentTarget.value; }}
        placeholder="alice@example.com"
        required
      />
    </div>
    <div class="form-group">
      <label>Password</label>
      <input
        type="password"
        value={password}
        oninput={(event) => { password = event.currentTarget.value; }}
        placeholder="any password"
        required
      />
    </div>
    {#if error}
      <div class="toast error">{error}</div>
    {/if}
    <button type="submit" class="primary" disabled={loading}>
      {loading ? "Logging in…" : "Login"}
    </button>
  </form>
  <div class="card" style="margin-top: 16px">
    <p>
      <strong>Try these accounts:</strong>
    </p>
    <p>alice@example.com — Admin (access to all routes)</p>
    <p>bob@example.com — Editor (no Admin page)</p>
    <p>carol@example.com — Viewer (no Admin page)</p>
    <p>Any password works in this demo.</p>
  </div>
</div>
