// examples/solid/search-schema/src/App.tsx
import { RouteView } from "@real-router/solid";

import { Home } from "./pages/Home";
import { Products } from "./pages/Products";
import { Layout } from "../../shared/Layout";

import type { JSX } from "solid-js";

const links = [
  { routeName: "home", label: "Home" },
  { routeName: "products", label: "Products" },
];

export function App(): JSX.Element {
  return (
    <Layout title="Real-Router — Search Schema" links={links}>
      <RouteView nodeName="">
        <RouteView.Match segment="home">
          <Home />
        </RouteView.Match>
        <RouteView.Match segment="products">
          <Products />
        </RouteView.Match>
        <RouteView.NotFound>
          <h1>404 — Page Not Found</h1>
        </RouteView.NotFound>
      </RouteView>
    </Layout>
  );
}

// examples/web/vue/search-schema/src/App.vue
<script setup lang="ts">
import { RouteView } from "@real-router/vue";

import Home from "./pages/Home.vue";
import Products from "./pages/Products.vue";
import Layout from "../../shared/Layout.vue";

const links = [
  { routeName: "home", label: "Home" },
  { routeName: "products", label: "Products" },
];
</script>

<template>
  <Layout title="Real-Router — Search Schema" :links="links">
    <RouteView nodeName="">
      <RouteView.Match segment="home">
        <Home />
      </RouteView.Match>
      <RouteView.Match segment="products">
        <Products />
      </RouteView.Match>
      <RouteView.NotFound>
        <h1>404 — Page Not Found</h1>
      </RouteView.NotFound>
    </RouteView>
  </Layout>
</template>
