// examples/svelte/search-schema/src/App.svelte
<script lang="ts">
  import { RouterProvider, RouteView } from "@real-router/svelte";
  import type { Router } from "@real-router/core";
  import Layout from "../../shared/Layout.svelte";
  import Home from "./pages/Home.svelte";
  import Products from "./pages/Products.svelte";

  let { router }: { router: Router } = $props();

  const links = [
    { routeName: "home", label: "Home" },
    { routeName: "products", label: "Products" },
  ];
</script>

<RouterProvider {router}>
  <Layout title="Real-Router — Search Schema" {links}>
    <RouteView nodeName="">
      {#snippet home()}
        <Home />
      {/snippet}
      {#snippet products()}
        <Products />
      {/snippet}
      {#snippet notFound()}
        <h1>404 — Page Not Found</h1>
      {/snippet}
    </RouteView>
  </Layout>
</RouterProvider>

// examples/web/vue/search-schema/src/App.vue
<script setup lang="ts">
import { RouteView } from "@real-router/vue";

import Home from "./pages/Home.vue";
import Products from "./pages/Products.vue";
import Layout from "../../shared/Layout.vue";

const links = [
  { routeName: "home", label: "Home" },
  { routeName: "products", label: "Products" },
];
</script>

<template>
  <Layout title="Real-Router — Search Schema" :links="links">
    <RouteView nodeName="">
      <RouteView.Match segment="home">
        <Home />
      </RouteView.Match>
      <RouteView.Match segment="products">
        <Products />
      </RouteView.Match>
      <RouteView.NotFound>
        <h1>404 — Page Not Found</h1>
      </RouteView.NotFound>
    </RouteView>
  </Layout>
</template>
