// examples/web/solid/ssr-examples/ssr-mixed/src/pages/Admin.tsx
import { Show, createSignal, onCleanup, onMount } from "solid-js";

import type { JSX } from "solid-js";

interface DashboardData {
  alerts: number;
  tickets: number;
}

export function AdminDashboard(): JSX.Element {
  const [data, setData] = createSignal<DashboardData | null>(null);

  onMount(() => {
    // Simulates a client-side fetch — server skipped the loader because of
    // `ssr: false`, so we fetch (or compute) the data here on hydration.
    const handle = setTimeout(() => {
      setData({ alerts: 3, tickets: 12 });
    }, 50);

    onCleanup(() => {
      clearTimeout(handle);
    });
  });

  return (
    <main data-testid="admin-dashboard">
      <h1>Admin dashboard (client-only)</h1>
      <Show
        when={data()}
        fallback={<p data-testid="admin-loading">Loading…</p>}
      >
        {(d) => (
          <p data-testid="admin-data">
            {d().alerts} alerts, {d().tickets} open tickets
          </p>
        )}
      </Show>
    </main>
  );
}

// examples/web/react/ssr-examples/ssr-mixed/src/pages/Admin.tsx
import { useEffect, useState } from "react";

interface DashboardData {
  alerts: number;
  tickets: number;
}

export function AdminDashboard() {
  const [data, setData] = useState<DashboardData | null>(null);

  useEffect(() => {
    // Simulates a client-side fetch — server skipped the loader because of
    // `ssr: false`, so we fetch (or compute) the data here on hydration.
    const handle = setTimeout(() => {
      setData({ alerts: 3, tickets: 12 });
    }, 50);

    return () => {
      clearTimeout(handle);
    };
  }, []);

  return (
    <main data-testid="admin-dashboard">
      <h1>Admin dashboard (client-only)</h1>
      {data === null ? (
        <p data-testid="admin-loading">Loading…</p>
      ) : (
        <p data-testid="admin-data">
          {data.alerts} alerts, {data.tickets} open tickets
        </p>
      )}
    </main>
  );
}
