// packages/solid/src/components/Streamed.tsx
import { Suspense } from "solid-js";

import type { JSX } from "solid-js";

export interface StreamedProps {
  /** Shown while any descendant `<Await>` / `createResource` suspends. */
  readonly fallback: JSX.Element;
  readonly children: JSX.Element;
}

/**
 * Cross-adapter alias for Solid's `<Suspense fallback={…}>`. Symmetric naming
 * with the React/Preact/Svelte/Vue/Angular `<Streamed>` components — pick
 * `<Streamed>` for cross-framework consistency, or use Solid's native
 * `<Suspense>` directly when team conventions prefer that.
 *
 * Solid's `<Suspense>` is a built-in primitive; out-of-order resolution +
 * splice scripts during `renderToStream` are part of the runtime. See
 * Solid's SSR docs for the wire-format details.
 */
export function Streamed(props: StreamedProps): JSX.Element {
  return <Suspense fallback={props.fallback}>{props.children}</Suspense>;
}

// packages/react/src/components/Streamed.tsx
import { Suspense } from "react";

import type { ReactNode } from "react";

export interface StreamedProps {
  /** Shown while any descendant `use(promise)` / `<Await>` is pending. */
  readonly fallback: ReactNode;
  readonly children: ReactNode;
}

/**
 * Cross-adapter alias for `<Suspense fallback={…}>`. Pairs with `<Await>`
 * for symmetry with `<Streamed>` boundaries in the SvelteKit / Solid
 * deferred-data conventions.
 *
 * ```tsx
 * <Streamed fallback={<Spinner />}>
 *   <Await<Review[]> name="reviews">
 *     {(reviews) => <ReviewList items={reviews} />}
 *   </Await>
 * </Streamed>
 * ```
 *
 * The component is a thin wrapper around React's native `<Suspense>` — no
 * additional behaviour. Use plain `<Suspense>` directly if you don't need
 * the cross-framework naming alignment.
 */
export function Streamed({ fallback, children }: StreamedProps): ReactNode {
  return <Suspense fallback={fallback}>{children}</Suspense>;
}
