// examples/web/preact/ssr-examples/ssr-mixed/src/pages/DocumentPage.tsx
import { useRoute } from "@real-router/preact";
import { getSsrDataMode } from "@real-router/ssr-data-plugin";
import { useEffect, useState } from "preact/hooks";

interface DocumentData {
  id: string;
  format: string;
  body: string;
}

export function DocumentPage() {
  const { route } = useRoute();
  const mode = getSsrDataMode(route);
  const ssrData = route.context.data as DocumentData | undefined;
  const [clientData, setClientData] = useState<DocumentData | null>(null);

  useEffect(() => {
    if (mode !== "client-only" || ssrData !== undefined) {
      return;
    }

    const handle = setTimeout(() => {
      setClientData({
        id: route.params.id as string,
        format: route.search.format as string,
        body: `(client) PDF placeholder for ${route.params.id as string}`,
      });
    }, 50);

    return () => {
      clearTimeout(handle);
    };
  }, [mode, ssrData, route.params.id, route.search.format]);

  const data = ssrData ?? clientData;

  return (
    <main data-testid="doc">
      <h1>Doc (mode: {mode})</h1>
      {data === null ? (
        <p data-testid="doc-loading">Loading…</p>
      ) : (
        <div>
          <p data-testid="doc-id">id: {data.id}</p>
          <p data-testid="doc-format">format: {data.format}</p>
          <p data-testid="doc-body">{data.body}</p>
        </div>
      )}
    </main>
  );
}

// examples/web/solid/ssr-examples/ssr-mixed/src/pages/DocumentPage.tsx
import { useRoute } from "@real-router/solid";
import { getSsrDataMode } from "@real-router/ssr-data-plugin";
import { Show, createSignal, onCleanup, onMount } from "solid-js";

import type { JSX } from "solid-js";

interface DocumentData {
  id: string;
  format: string;
  body: string;
}

export function DocumentPage(): JSX.Element {
  const routeState = useRoute();
  const mode = (): "full" | "data-only" | "client-only" =>
    getSsrDataMode(routeState().route);
  const ssrData = (): DocumentData | undefined =>
    routeState().route.context.data as DocumentData | undefined;
  const [clientData, setClientData] = createSignal<DocumentData | null>(null);

  onMount(() => {
    if (mode() !== "client-only" || ssrData() !== undefined) {
      return;
    }

    const params = routeState().route.params;
    const search = routeState().route.search;
    const handle = setTimeout(() => {
      setClientData({
        id: params.id as string,
        format: search.format as string,
        body: `(client) PDF placeholder for ${params.id as string}`,
      });
    }, 50);

    onCleanup(() => {
      clearTimeout(handle);
    });
  });

  const data = (): DocumentData | null | undefined => ssrData() ?? clientData();

  return (
    <main data-testid="doc">
      <h1>Doc (mode: {mode()})</h1>
      <Show when={data()} fallback={<p data-testid="doc-loading">Loading…</p>}>
        {(d) => (
          <div>
            <p data-testid="doc-id">id: {d().id}</p>
            <p data-testid="doc-format">format: {d().format}</p>
            <p data-testid="doc-body">{d().body}</p>
          </div>
        )}
      </Show>
    </main>
  );
}
