// examples/web/preact/ssr-examples/ssr-streaming/src/components/ProductsList.tsx
import { Link, useRoute } from "@real-router/preact";

import type { ProductsListData } from "../router/loaders";
import type { JSX } from "preact";

export function ProductsList(): JSX.Element {
  const { route } = useRoute();
  const data = route.context.data as ProductsListData | undefined;

  return (
    <div>
      <h1>Products</h1>
      <ul data-testid="products-list">
        {(data?.products ?? []).map((product) => (
          <li key={product.id}>
            <Link
              routeName="products.detail"
              routeParams={{ id: product.id }}
              data-testid={`product-link-${product.id}`}
            >
              {product.name}
            </Link>
            {" — "}${product.price.toFixed(2)}
          </li>
        ))}
      </ul>
    </div>
  );
}

// examples/web/vue/ssr-examples/ssr-streaming/src/components/ProductsList.vue
<script setup lang="ts">
import { Link, useRoute } from "@real-router/vue";
import { computed } from "vue";

import type { ProductsListData } from "../router/loaders";

const { route } = useRoute();
const data = computed<ProductsListData>(
  () => (route.value.context.data as ProductsListData | undefined) ?? { products: [] },
);
</script>

<template>
  <section data-testid="products-list">
    <h1>Products</h1>
    <ul>
      <li
        v-for="product in data.products"
        :key="product.id"
        :data-product-id="product.id"
      >
        <Link routeName="products.detail" :routeParams="{ id: product.id }">
          {{ product.name }}
        </Link>
        — ${{ product.price }}
      </li>
    </ul>
  </section>
</template>
