// examples/web/solid/ssr-examples/ssr-streaming/src/components/ProductDetail.tsx
import { useRoute } from "@real-router/solid";
import { ErrorBoundary, Show, Suspense } from "solid-js";

import { RelatedItems } from "./RelatedItems";
import { Reviews } from "./Reviews";

import type { ProductDetailData } from "../router/loaders";
import type { JSX } from "solid-js";

export function ProductDetail(): JSX.Element {
  const routeState = useRoute();
  const data = (): ProductDetailData | undefined =>
    routeState().route.context.data as ProductDetailData | undefined;

  return (
    <Show
      when={data()}
      fallback={<p data-testid="product-not-found">Product not found.</p>}
      keyed
    >
      {(d) => (
        <article data-testid="product-detail" data-product-id={d.product.id}>
          <h1 data-testid="product-name">{d.product.name}</h1>
          <p data-testid="product-price">${d.product.price}</p>
          <p data-testid="product-description">{d.product.description}</p>

          <ErrorBoundary
            fallback={(err: Error) => (
              <p data-testid="reviews-error">
                Reviews unavailable: {err.message}
              </p>
            )}
          >
            <Suspense
              fallback={<p data-testid="reviews-fallback">Loading reviews…</p>}
            >
              <Reviews productId={d.product.id} />
            </Suspense>
          </ErrorBoundary>

          <Suspense
            fallback={
              <p data-testid="related-fallback">Loading related items…</p>
            }
          >
            <RelatedItems productId={d.product.id} />
          </Suspense>
        </article>
      )}
    </Show>
  );
}

// examples/web/vue/ssr-examples/ssr-streaming/src/components/ProductDetail.vue
<script setup lang="ts">
import { useRoute } from "@real-router/vue";
import { computed } from "vue";

import RelatedItems from "./RelatedItems.vue";
import Reviews from "./Reviews.vue";
import ReviewsErrorBoundary from "./ReviewsErrorBoundary.vue";

import type { ProductDetailData } from "../router/loaders";

const { route } = useRoute();
const data = computed<ProductDetailData | undefined>(
  () => route.value.context.data as ProductDetailData | undefined,
);
</script>

<template>
  <p v-if="!data" data-testid="product-not-found">Product not found.</p>
  <article
    v-else
    data-testid="product-detail"
    :data-product-id="data.product.id"
  >
    <h1 data-testid="product-name">{{ data.product.name }}</h1>
    <p data-testid="product-price">${{ data.product.price }}</p>
    <p data-testid="product-description">{{ data.product.description }}</p>

    <ReviewsErrorBoundary>
      <Suspense>
        <Reviews :productId="data.product.id" />
        <template #fallback>
          <p data-testid="reviews-fallback">Loading reviews…</p>
        </template>
      </Suspense>
    </ReviewsErrorBoundary>

    <Suspense>
      <RelatedItems :productId="data.product.id" />
      <template #fallback>
        <p data-testid="related-fallback">Loading related items…</p>
      </template>
    </Suspense>
  </article>
</template>
