// examples/web/solid/ssr-examples/ssg/src/pages/UsersList.tsx
import { Link, useRoute } from "@real-router/solid";
import { For } from "solid-js";

import type { UsersListData } from "../router/loaders";
import type { JSX } from "solid-js";

const EMPTY_DATA: UsersListData = { users: [] };

export function UsersList(): JSX.Element {
  const routeState = useRoute();
  const data = (): UsersListData =>
    (routeState().route.context.data as UsersListData | undefined) ?? EMPTY_DATA;

  return (
    <div>
      <h2>All Users</h2>
      <ul>
        <For each={data().users}>
          {(user) => (
            <li>
              <Link routeName="users.profile" routeParams={{ id: user.id }}>
                {user.name}
              </Link>
            </li>
          )}
        </For>
      </ul>
    </div>
  );
}

// examples/web/react/ssr-examples/ssg/src/pages/UsersList.tsx
import { Link, useRoute } from "@real-router/react";

import type { UsersListData } from "../router/loaders";
import type { JSX } from "react";

export function UsersList(): JSX.Element {
  const { route } = useRoute();
  const data = (route.context.data ?? { users: [] }) as UsersListData;

  return (
    <div>
      <h2>All Users</h2>
      <ul>
        {data.users.map((user) => (
          <li key={user.id}>
            <Link routeName="users.profile" routeParams={{ id: user.id }}>
              {user.name}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}
