// examples/web/vue/ssr-examples/ssr-streaming/src/components/ReviewsErrorBoundary.vue
<script setup lang="ts">
import { onErrorCaptured, ref } from "vue";

// Vue's `onErrorCaptured` is the equivalent of React's ErrorBoundary class.
// Returning `false` from the hook stops error propagation. Scope is narrow:
// wraps just the deferred Reviews <Suspense> so failures don't crash the
// surrounding ProductDetail tree.
const error = ref<Error | null>(null);

onErrorCaptured((capturedError) => {
  error.value =
    capturedError instanceof Error ? capturedError : new Error(String(capturedError));
  console.warn("[Reviews] section failed:", error.value.message);
  return false;
});
</script>

<template>
  <p v-if="error" data-testid="reviews-error">
    Reviews unavailable: {{ error.message }}
  </p>
  <slot v-else />
</template>

// examples/web/react/ssr-examples/ssr-streaming/src/components/ReviewsErrorBoundary.tsx
import { Component } from "react";

import type { ErrorInfo, ReactElement, ReactNode } from "react";

interface ReviewsErrorBoundaryProps {
  readonly children: ReactNode;
}

interface ReviewsErrorBoundaryState {
  readonly error: Error | null;
}

// Class component because React 19's `use(rejectedPromise)` throws during render —
// only ErrorBoundary class API catches render-thrown errors. The boundary
// scope is intentionally narrow: it wraps just the deferred Reviews section
// so failures don't crash the surrounding ProductDetail tree.
export class ReviewsErrorBoundary extends Component<
  ReviewsErrorBoundaryProps,
  ReviewsErrorBoundaryState
> {
  state: ReviewsErrorBoundaryState = { error: null };

  static getDerivedStateFromError(error: Error): ReviewsErrorBoundaryState {
    return { error };
  }

  componentDidCatch(error: Error, info: ErrorInfo): void {
    console.warn("[Reviews] section failed:", error.message, info.componentStack);
  }

  render(): ReactElement {
    if (this.state.error) {
      return (
        <p data-testid="reviews-error">
          Reviews unavailable: {this.state.error.message}
        </p>
      );
    }

    return <>{this.props.children}</>;
  }
}
