// packages/react/src/components/Await.tsx
import { use } from "react";

import { useDeferred } from "../hooks/useDeferred";

import type { ReactNode } from "react";

export interface AwaitProps<T> {
  /** Deferred key declared in the loader's `defer({ deferred: { <name>: ... } })`. */
  readonly name: string;
  /** Render the resolved value. Suspends while pending; throws inside the
   * nearest Error Boundary on rejection. */
  readonly children: (value: T) => ReactNode;
}

/**
 * Ergonomic wrapper around `useDeferred(name)` + React 19's `use(promise)`.
 *
 * ```tsx
 * <Suspense fallback={<Spinner />}>
 *   <Await<Review[]> name="reviews">
 *     {(reviews) => <ReviewList items={reviews} />}
 *   </Await>
 * </Suspense>
 * ```
 *
 * Equivalent to:
 *
 * ```tsx
 * function Inner() {
 *   const reviews = use(useDeferred<Review[]>("reviews"));
 *   return <ReviewList items={reviews} />;
 * }
 * ```
 *
 * Pick `<Await>` for cross-adapter consistency with the SvelteKit
 * `{#await}` / Solid `<Await/>` shape; pick the inline `use(useDeferred(...))`
 * form if you prefer one fewer abstraction.
 */
export function Await<T = unknown>({
  name,
  children,
}: AwaitProps<T>): ReactNode {
  const value = use(useDeferred<T>(name));

  return children(value);
}

// packages/solid/src/components/Await.tsx
import { createResource } from "solid-js";

import { useDeferred } from "../hooks/useDeferred";

import type { JSX } from "solid-js";

export interface AwaitProps<T> {
  /** Deferred key declared in the loader's `defer({ deferred: { <name>: ... } })`. */
  readonly name: string;
  /** Render the resolved value. Surrounding `<Suspense>` shows fallback while
   * pending; rejection bubbles through Solid's `<ErrorBoundary>`. */
  readonly children: (value: T) => JSX.Element;
}

/**
 * Reads `useDeferred(name)` and hands the resolved value to the render-prop.
 * Wraps the deferred promise in `createResource` so Solid's reactivity tracks
 * resolution and `<Suspense>` gets the standard suspend signal.
 *
 * ```tsx
 * <Streamed fallback={<Spinner />}>
 *   <Await<Review[]> name="reviews">
 *     {(reviews) => <ReviewList items={reviews} />}
 *   </Await>
 * </Streamed>
 * ```
 *
 * Implementation: returns a Solid accessor (function child) that reads
 * `resource()` — this both (a) triggers `<Suspense>` suspension while pending
 * and (b) re-throws on `errored` for the nearest `<ErrorBoundary>` to catch.
 * The render-prop is gated on `resource.state === "ready"` rather than on
 * truthiness so falsy resolved values (`0`, `false`, `null`, `""`) still
 * reach `props.children`.
 */
export function Await<T = unknown>(props: AwaitProps<T>): JSX.Element {
  const promiseAccessor = useDeferred<T>(props.name);
  const [resource] = createResource(promiseAccessor, (promise) => promise);

  return (() => {
    const value = resource();

    if (resource.state !== "ready") {
      return;
    }

    return props.children(value as T);
  }) as unknown as JSX.Element;
}
