// packages/preact/src/components/Streamed.tsx
import { Suspense } from "preact/compat";

import type { ComponentChildren } from "preact";

export interface StreamedProps {
  /** Shown while any descendant `<Await>` / `use(promise)`-equivalent suspends. */
  readonly fallback: ComponentChildren;
  readonly children: ComponentChildren;
}

/**
 * Cross-adapter alias for `<Suspense fallback={…}>` from `preact/compat`.
 * Pairs with `<Await>` for symmetry with the React/Solid/Svelte/Vue/Angular
 * SSR streaming naming.
 *
 * Preact's `Suspense` is part of `preact/compat` (experimental). For
 * production streaming the preact-render-to-string toolchain is required.
 */
export function Streamed({
  fallback,
  children,
}: StreamedProps): ComponentChildren {
  return <Suspense fallback={fallback}>{children}</Suspense>;
}

// packages/solid/src/components/Streamed.tsx
import { Suspense } from "solid-js";

import type { JSX } from "solid-js";

export interface StreamedProps {
  /** Shown while any descendant `<Await>` / `createResource` suspends. */
  readonly fallback: JSX.Element;
  readonly children: JSX.Element;
}

/**
 * Cross-adapter alias for Solid's `<Suspense fallback={…}>`. Symmetric naming
 * with the React/Preact/Svelte/Vue/Angular `<Streamed>` components — pick
 * `<Streamed>` for cross-framework consistency, or use Solid's native
 * `<Suspense>` directly when team conventions prefer that.
 *
 * Solid's `<Suspense>` is a built-in primitive; out-of-order resolution +
 * splice scripts during `renderToStream` are part of the runtime. See
 * Solid's SSR docs for the wire-format details.
 */
export function Streamed(props: StreamedProps): JSX.Element {
  return <Suspense fallback={props.fallback}>{props.children}</Suspense>;
}
