// examples/web/vue/animation-examples/motion-animations/src/pages/ProductDetail.vue
<script setup lang="ts">
import { Link, useRoute } from "@real-router/vue";
import { computed } from "vue";

const COVERS: Partial<Record<string, { name: string; color: string }>> = {
  1: { name: "Crimson Flask", color: "#b91c1c" },
  2: { name: "Azure Orb", color: "#1d4ed8" },
  3: { name: "Emerald Prism", color: "#047857" },
  4: { name: "Amber Cube", color: "#b45309" },
  5: { name: "Violet Sphere", color: "#6d28d9" },
  6: { name: "Slate Block", color: "#334155" },
};

const { route } = useRoute<{ id: string }>();
const id = computed(() => route.value?.params.id ?? "1");
const product = computed(() => COVERS[id.value]);
</script>

<template>
  <div v-if="product">
    <h2>{{ product.name }}</h2>
    <div
      class="product-cover"
      :style="{ backgroundColor: product.color }"
      aria-hidden="true"
    />
    <p>
      Note: no library-driven hero morph here. Vue's built-in
      <code>&lt;Transition&gt;</code> is per-element entry/exit only —
      it does not pair elements across the route boundary. For an
      inverse-FLIP hero morph in Vue, see
      <code>route-animations/</code> → <code>useHeroMorph</code>:
      capture rect on <code>useRouteExit</code>, animate via WAAPI on
      <code>navigator.subscribe</code>.
    </p>
    <p>
      <Link routeName="products" activeStrict>
        ← Back to products
      </Link>
    </p>
  </div>
  <div v-else>
    <h2>Unknown product</h2>
    <Link routeName="products" activeStrict>
      Back to products
    </Link>
  </div>
</template>

// examples/web/solid/animation-examples/motion-animations/src/pages/ProductDetail.tsx
import { Link, useRoute } from "@real-router/solid";
import { Show, createMemo } from "solid-js";

import type { JSX } from "solid-js";

const COVERS: Partial<Record<string, { name: string; color: string }>> = {
  1: { name: "Crimson Flask", color: "#b91c1c" },
  2: { name: "Azure Orb", color: "#1d4ed8" },
  3: { name: "Emerald Prism", color: "#047857" },
  4: { name: "Amber Cube", color: "#b45309" },
  5: { name: "Violet Sphere", color: "#6d28d9" },
  6: { name: "Slate Block", color: "#334155" },
};

export function ProductDetail(): JSX.Element {
  const routeState = useRoute<{ id: string }>();
  const id = createMemo(() => routeState().route.params.id);
  const product = createMemo(() => COVERS[id()]);

  return (
    <Show
      when={product()}
      fallback={
        <div>
          <h2>Unknown product</h2>
          <Link routeName="products" activeStrict>
            Back to products
          </Link>
        </div>
      }
    >
      {(productAccessor) => (
        <div>
          <h2>{productAccessor().name}</h2>
          <div
            class="product-cover"
            style={{ "background-color": productAccessor().color }}
            aria-hidden="true"
          />
          <p>
            Note: no library-driven hero morph here. Motion One does not ship{" "}
            <code>layoutId</code>, so the thumbnail's coloured square cannot be
            paired with this cover via a single prop. For an inverse-FLIP hero
            morph in Solid, see <code>route-animations/</code> →{" "}
            <code>useHeroMorph</code>: capture rect on <code>useRouteExit</code>
            , animate via WAAPI on <code>navigator.subscribe</code>.
          </p>
          <p>
            <Link routeName="products" activeStrict>
              ← Back to products
            </Link>
          </p>
        </div>
      )}
    </Show>
  );
}
