// examples/web/react/ssr-examples/ssg/src/pages/UsersList.tsx
import { Link, useRoute } from "@real-router/react";

import type { UsersListData } from "../router/loaders";
import type { JSX } from "react";

export function UsersList(): JSX.Element {
  const { route } = useRoute();
  const data = (route.context.data ?? { users: [] }) as UsersListData;

  return (
    <div>
      <h2>All Users</h2>
      <ul>
        {data.users.map((user) => (
          <li key={user.id}>
            <Link routeName="users.profile" routeParams={{ id: user.id }}>
              {user.name}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

// examples/web/vue/ssr-examples/ssg/src/pages/UsersList.vue
<script setup lang="ts">
import { Link, useRoute } from "@real-router/vue";
import { computed } from "vue";

import type { UsersListData } from "../router/loaders";

const { route } = useRoute();
const data = computed<UsersListData>(
  () =>
    (route.value.context.data as UsersListData | undefined) ?? { users: [] },
);
</script>

<template>
  <div>
    <h2>All Users</h2>
    <ul>
      <li v-for="user in data.users" :key="user.id">
        <Link routeName="users.profile" :routeParams="{ id: user.id }">
          {{ user.name }}
        </Link>
      </li>
    </ul>
  </div>
</template>
