// packages/react-router6/modules/types.ts
// packages/react-real-router/modules/types.ts

import type { MouseEvent, ReactNode } from "react";
import type { Params, Router, RouterError, State } from "router6";

export interface RouteState<
  P extends Params = Params,
  MP extends Params = Params,
> {
  route: State<P, MP> | undefined;
  previousRoute?: State | undefined;
}

export type RouteContext = {
  router: Router;
} & RouteState;

export type UnsubscribeFn = () => void;

export interface BaseLinkProps {
  [key: string]: unknown;
  router: Router;
  routeName: string;
  routeParams?: Params;
  routeOptions?: {
    [key: string]: unknown;
    reload?: boolean;
    replace?: boolean;
  };
  className?: string;
  activeClassName?: string;
  activeStrict?: boolean;
  ignoreQueryParams?: boolean;
  onClick?: (evt: MouseEvent<HTMLAnchorElement>) => void;
  successCallback?: (state?: State) => void;
  errorCallback?: (err: RouterError) => void;
  target?: string;
  children?: ReactNode;
  previousRoute?: State;
}

export interface ActiveRouteOptions {
  activeStrict?: boolean;
  ignoreQueryParams?: boolean;
}

// packages/solid/src/types.ts
import type { NavigationOptions, Params, State } from "@real-router/core";
import type { JSX } from "solid-js";

export interface RouteState<P extends Params = Params> {
  route: State<P> | undefined;
  previousRoute?: State | undefined;
}

export interface LinkProps<P extends Params = Params> extends Omit<
  JSX.HTMLAttributes<HTMLAnchorElement>,
  "onClick"
> {
  routeName: string;
  routeParams?: P;
  routeOptions?: NavigationOptions;
  activeClassName?: string;
  activeStrict?: boolean;
  ignoreQueryParams?: boolean;
  target?: string;
  onClick?: (evt: MouseEvent) => void;
}
