// examples/web/react/animation-examples/view-transitions/src/pages/ProductsList.tsx
import { Link, useRoute } from "@real-router/react";
import { useMemo } from "react";

import type { CSSProperties, JSX } from "react";

interface Product {
  id: string;
  name: string;
  color: string;
}

const PRODUCTS: Product[] = [
  { id: "1", name: "Crimson Flask", color: "#b91c1c" },
  { id: "2", name: "Azure Orb", color: "#1d4ed8" },
  { id: "3", name: "Emerald Prism", color: "#047857" },
  { id: "4", name: "Amber Cube", color: "#b45309" },
  { id: "5", name: "Violet Sphere", color: "#6d28d9" },
  { id: "6", name: "Slate Block", color: "#334155" },
];

type SortDirection = "asc" | "desc";

export function ProductsList(): JSX.Element {
  const { route } = useRoute<{ sort?: SortDirection }>();
  const sort: SortDirection = route?.params.sort === "desc" ? "desc" : "asc";

  const items = useMemo(() => {
    const sorted = PRODUCTS.toSorted((left, right) =>
      left.name.localeCompare(right.name),
    );

    return sort === "desc" ? sorted.toReversed() : sorted;
  }, [sort]);

  return (
    <>
      <div className="vt-products-toolbar">
        <span>Sort:</span>
        <Link
          routeName="products"
          routeParams={{ sort: "asc" }}
          ignoreQueryParams={false}
        >
          A → Z
        </Link>
        {" · "}
        <Link
          routeName="products"
          routeParams={{ sort: "desc" }}
          ignoreQueryParams={false}
        >
          Z → A
        </Link>
        {" · "}
        <strong>current: {sort}</strong>
      </div>

      <ul className="vt-product-list" data-vt-scope="product-list">
        {items.map((product) => (
          <li
            key={product.id}
            className="vt-product-card"
            style={
              {
                "--vt-card-name": `vt-card-${product.id}`,
              } as CSSProperties
            }
          >
            <Link routeName="products.detail" routeParams={{ id: product.id }}>
              <span
                className="vt-product-thumb"
                data-product-id={product.id}
                style={{ backgroundColor: product.color }}
                aria-hidden="true"
              />
              <span className="vt-product-name">{product.name}</span>
            </Link>
          </li>
        ))}
      </ul>
    </>
  );
}

// examples/web/vue/animation-examples/view-transitions/src/pages/ProductsList.vue
<script setup lang="ts">
import { Link, useRoute } from "@real-router/vue";
import { computed } from "vue";

interface Product {
  id: string;
  name: string;
  color: string;
}

const PRODUCTS: Product[] = [
  { id: "1", name: "Crimson Flask", color: "#b91c1c" },
  { id: "2", name: "Azure Orb", color: "#1d4ed8" },
  { id: "3", name: "Emerald Prism", color: "#047857" },
  { id: "4", name: "Amber Cube", color: "#b45309" },
  { id: "5", name: "Violet Sphere", color: "#6d28d9" },
  { id: "6", name: "Slate Block", color: "#334155" },
];

type SortDirection = "asc" | "desc";

const { route } = useRoute<{ sort?: SortDirection }>();

const sort = computed<SortDirection>(() =>
  route.value?.params.sort === "desc" ? "desc" : "asc",
);

const items = computed(() => {
  const sorted = PRODUCTS.toSorted((left, right) =>
    left.name.localeCompare(right.name),
  );

  return sort.value === "desc" ? sorted.toReversed() : sorted;
});
</script>

<template>
  <div class="vt-products-toolbar">
    <span>Sort:</span>
    <Link
      routeName="products"
      :routeParams="{ sort: 'asc' }"
      :ignoreQueryParams="false"
    >
      A → Z
    </Link>
    {{ " · " }}
    <Link
      routeName="products"
      :routeParams="{ sort: 'desc' }"
      :ignoreQueryParams="false"
    >
      Z → A
    </Link>
    {{ " · " }}
    <strong>current: {{ sort }}</strong>
  </div>

  <ul class="vt-product-list" data-vt-scope="product-list">
    <li
      v-for="product in items"
      :key="product.id"
      class="vt-product-card"
      :style="{ '--vt-card-name': `vt-card-${product.id}` }"
    >
      <Link
        routeName="products.detail"
        :routeParams="{ id: product.id }"
      >
        <span
          class="vt-product-thumb"
          :data-product-id="product.id"
          :style="{ backgroundColor: product.color }"
          aria-hidden="true"
        />
        <span class="vt-product-name">{{ product.name }}</span>
      </Link>
    </li>
  </ul>
</template>
