// examples/react/shared/Layout.tsx
import { Link } from "@real-router/react";

import type { ReactNode } from "react";

interface NavLink {
  routeName: string;
  label: string;
}

interface LayoutProps {
  title: string;
  links: NavLink[];
  children: ReactNode;
}

export function Layout({ title, links, children }: LayoutProps): ReactNode {
  return (
    <div className="app">
      <header className="header">{title}</header>
      <aside className="sidebar">
        {links.map((link) => (
          <Link
            key={link.routeName}
            routeName={link.routeName}
            activeClassName="active"
          >
            {link.label}
          </Link>
        ))}
      </aside>
      <main className="content">{children}</main>
      <footer className="footer">@real-router/react</footer>
    </div>
  );
}

// examples/solid/shared/Layout.tsx
import { Link } from "@real-router/solid";
import { For } from "solid-js";

import type { JSX } from "solid-js";

interface NavLink {
  routeName: string;
  label: string;
}

interface LayoutProps {
  title: string;
  links: NavLink[];
  children: JSX.Element;
}

export function Layout(props: LayoutProps): JSX.Element {
  return (
    <div class="app">
      <header class="header">{props.title}</header>
      <aside class="sidebar">
        <For each={props.links}>
          {(link) => (
            <Link routeName={link.routeName} activeClassName="active">
              {link.label}
            </Link>
          )}
        </For>
      </aside>
      <main class="content">{props.children}</main>
      <footer class="footer">@real-router/solid</footer>
    </div>
  );
}
