// examples/angular/dynamic-routes/src/pages/home.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "home-page",
  template: `
    <div>
      <h1>Home</h1>
      <p>
        Toggle the feature flags in the sidebar to add or remove routes at
        runtime. The sidebar and route tree panel update instantly.
      </p>
      <p>
        If you are on an active route when you disable it, you are redirected
        here automatically.
      </p>
    </div>
  `,
})
export class HomeComponent {}

// examples/web/vue/dynamic-routes/src/pages/Home.vue
<template>
  <div>
    <h1>Home</h1>
    <p>
      Toggle the feature flags in the sidebar to add or remove routes at
      runtime. The sidebar and route tree panel update instantly.
    </p>
    <p>
      If you are on an active route when you disable it, you are redirected here
      automatically.
    </p>
  </div>
</template>
