// packages/preact/src/hooks/useRouterTransition.tsx
import { createTransitionSource } from "@real-router/sources";
import { useMemo } from "preact/hooks";

import { useSyncExternalStore } from "../useSyncExternalStore";
import { useRouter } from "./useRouter";

import type { RouterTransitionSnapshot } from "@real-router/sources";

export function useRouterTransition(): RouterTransitionSnapshot {
  const router = useRouter();

  const store = useMemo(() => createTransitionSource(router), [router]);

  return useSyncExternalStore(
    store.subscribe,
    store.getSnapshot,
    store.getSnapshot,
  );
}

// packages/solid/src/hooks/useRouterTransition.tsx
import { createTransitionSource } from "@real-router/sources";

import { createSignalFromSource } from "../createSignalFromSource";
import { useRouter } from "./useRouter";

import type { RouterTransitionSnapshot } from "@real-router/sources";
import type { Accessor } from "solid-js";

export function useRouterTransition(): Accessor<RouterTransitionSnapshot> {
  const router = useRouter();
  const store = createTransitionSource(router);

  return createSignalFromSource(store);
}
