// examples/svelte/search-schema/src/pages/Home.svelte
<script lang="ts">
  import { Link } from "@real-router/svelte";
</script>

<div>
  <h1>Search Schema Plugin</h1>
  <p>
    This example demonstrates <code>@real-router/search-schema-plugin</code> —
    Zod-based validation and coercion of URL search parameters.
  </p>
  <p>
    Navigate to
    <Link routeName="products">Products</Link>
    to see validated search params in action.
  </p>
  <div class="card">
    <p><strong>Features:</strong></p>
    <ul style="margin-top: 8px; padding-left: 20px">
      <li>Type coercion — string "2" becomes number 2</li>
      <li>Default values — missing params get schema defaults</li>
      <li>Validation — invalid values are replaced with defaults</li>
      <li>Enum enforcement — sort must be "name", "price", or "date"</li>
    </ul>
  </div>
</div>

// examples/web/preact/search-schema/src/pages/Home.tsx
import { Link } from "@real-router/preact";

import type { JSX } from "preact";

export function Home(): JSX.Element {
  return (
    <div>
      <h1>Search Schema Plugin</h1>
      <p>
        This example demonstrates <code>@real-router/search-schema-plugin</code>{" "}
        — runtime validation of URL search parameters using Zod schemas.
      </p>
      <div className="card">
        <h3>What it does</h3>
        <ul style={{ paddingLeft: "20px", marginTop: "8px" }}>
          <li>
            Validates <code>page</code>, <code>sort</code>, and <code>q</code>{" "}
            params against a Zod schema
          </li>
          <li>Invalid params are stripped and replaced with route defaults</li>
          <li>
            Uses <code>numberFormat: &quot;auto&quot;</code> so{" "}
            <code>page</code> is a real number, not a string
          </li>
        </ul>
      </div>
      <div style={{ marginTop: "16px" }}>
        <Link routeName="products">
          <button className="primary">Go to Products</button>
        </Link>
      </div>
    </div>
  );
}
