// examples/web/svelte/ssr-examples/ssr-mixed/src/pages/Doc.svelte
<script lang="ts">
  import { getSsrDataMode } from "@real-router/ssr-data-plugin";
  import { useRoute } from "@real-router/svelte";
  import { onDestroy, onMount } from "svelte";

  interface DocData {
    id: string;
    format: string;
    body: string;
  }

  const { route } = useRoute<{ id: string }>();
  const mode = $derived(getSsrDataMode(route.current));
  const ssrData = $derived(route.current.context.data as DocData | undefined);
  let clientData = $state<DocData | null>(null);
  let handle: ReturnType<typeof setTimeout> | undefined;

  onMount(() => {
    if (mode !== "client-only" || ssrData !== undefined) {return;}

    const params = route.current.params;
    const search = route.current.search;

    handle = setTimeout(() => {
      clientData = {
        id: params.id,
        format: String(search.format),
        body: `(client) PDF placeholder for ${params.id}`,
      };
    }, 50);
  });

  onDestroy(() => {
    if (handle !== undefined) {clearTimeout(handle);}
  });

  const data = $derived(ssrData ?? clientData);
</script>

<main data-testid="doc">
  <h1>Doc (mode: {mode})</h1>
  {#if !data}
    <p data-testid="doc-loading">Loading…</p>
  {:else}
    <div>
      <p data-testid="doc-id">id: {data.id}</p>
      <p data-testid="doc-format">format: {data.format}</p>
      <p data-testid="doc-body">{data.body}</p>
    </div>
  {/if}
</main>

// examples/web/vue/ssr-examples/ssr-mixed/src/pages/Doc.vue
<script setup lang="ts">
import { getSsrDataMode } from "@real-router/ssr-data-plugin";
import { useRoute } from "@real-router/vue";
import { computed, onMounted, onUnmounted, ref } from "vue";

interface DocData {
  id: string;
  format: string;
  body: string;
}

const { route } = useRoute<{ id: string }>();
const mode = computed(() => getSsrDataMode(route.value));
const ssrData = computed(() => route.value.context.data as DocData | undefined);
const clientData = ref<DocData | null>(null);
let handle: ReturnType<typeof setTimeout> | undefined;

onMounted(() => {
  if (mode.value !== "client-only" || ssrData.value !== undefined) {
    return;
  }

  handle = setTimeout(() => {
    clientData.value = {
      id: route.value.params.id,
      format: String(route.value.search.format),
      body: `(client) PDF placeholder for ${route.value.params.id}`,
    };
  }, 50);
});

onUnmounted(() => {
  if (handle !== undefined) {
    clearTimeout(handle);
  }
});

const data = computed(() => ssrData.value ?? clientData.value);
</script>

<template>
  <main data-testid="doc">
    <h1>Doc (mode: {{ mode }})</h1>
    <p v-if="!data" data-testid="doc-loading">Loading…</p>
    <div v-else>
      <p data-testid="doc-id">id: {{ data.id }}</p>
      <p data-testid="doc-format">format: {{ data.format }}</p>
      <p data-testid="doc-body">{{ data.body }}</p>
    </div>
  </main>
</template>
