// examples/web/react/ssr-examples/ssr-mixed/src/pages/Doc.tsx
import { useRoute } from "@real-router/react";
import { getSsrDataMode } from "@real-router/ssr-data-plugin";
import { useEffect, useState } from "react";

interface DocData {
  id: string;
  format: string;
  body: string;
}

export function Doc() {
  const { route } = useRoute();
  const mode = getSsrDataMode(route);
  const ssrData = route.context.data as DocData | undefined;
  const [clientData, setClientData] = useState<DocData | null>(null);

  useEffect(() => {
    if (mode !== "client-only" || ssrData !== undefined) {
      return;
    }

    const handle = setTimeout(() => {
      setClientData({
        id: String(route.params.id),
        format: String(route.search.format),
        body: `(client) PDF placeholder for ${String(route.params.id)}`,
      });
    }, 50);

    return () => {
      clearTimeout(handle);
    };
  }, [mode, ssrData, route.params.id, route.search.format]);

  const data = ssrData ?? clientData;

  return (
    <main data-testid="doc">
      <h1>Doc (mode: {mode})</h1>
      {data === null || data === undefined ? (
        <p data-testid="doc-loading">Loading…</p>
      ) : (
        <div>
          <p data-testid="doc-id">id: {data.id}</p>
          <p data-testid="doc-format">format: {data.format}</p>
          <p data-testid="doc-body">{data.body}</p>
        </div>
      )}
    </main>
  );
}

// examples/web/vue/ssr-examples/ssr-mixed/src/pages/Doc.vue
<script setup lang="ts">
import { getSsrDataMode } from "@real-router/ssr-data-plugin";
import { useRoute } from "@real-router/vue";
import { computed, onMounted, onUnmounted, ref } from "vue";

interface DocData {
  id: string;
  format: string;
  body: string;
}

const { route } = useRoute<{ id: string }>();
const mode = computed(() => getSsrDataMode(route.value));
const ssrData = computed(() => route.value.context.data as DocData | undefined);
const clientData = ref<DocData | null>(null);
let handle: ReturnType<typeof setTimeout> | undefined;

onMounted(() => {
  if (mode.value !== "client-only" || ssrData.value !== undefined) {
    return;
  }

  handle = setTimeout(() => {
    clientData.value = {
      id: route.value.params.id,
      format: String(route.value.search.format),
      body: `(client) PDF placeholder for ${route.value.params.id}`,
    };
  }, 50);
});

onUnmounted(() => {
  if (handle !== undefined) {
    clearTimeout(handle);
  }
});

const data = computed(() => ssrData.value ?? clientData.value);
</script>

<template>
  <main data-testid="doc">
    <h1>Doc (mode: {{ mode }})</h1>
    <p v-if="!data" data-testid="doc-loading">Loading…</p>
    <div v-else>
      <p data-testid="doc-id">id: {{ data.id }}</p>
      <p data-testid="doc-format">format: {{ data.format }}</p>
      <p data-testid="doc-body">{{ data.body }}</p>
    </div>
  </main>
</template>
