// examples/react/shared/Layout.tsx
import { Link } from "@real-router/react";

import type { ReactNode } from "react";

interface NavLink {
  routeName: string;
  label: string;
}

interface LayoutProps {
  title: string;
  links: NavLink[];
  children: ReactNode;
}

export function Layout({ title, links, children }: LayoutProps): ReactNode {
  return (
    <div className="app">
      <header className="header">{title}</header>
      <aside className="sidebar">
        {links.map((link) => (
          <Link
            key={link.routeName}
            routeName={link.routeName}
            activeClassName="active"
          >
            {link.label}
          </Link>
        ))}
      </aside>
      <main className="content">{children}</main>
      <footer className="footer">@real-router/react</footer>
    </div>
  );
}

// examples/vue/shared/Layout.vue
<script setup lang="ts">
import { Link } from "@real-router/vue";

interface NavLink {
  routeName: string;
  label: string;
}

defineProps<{
  title: string;
  links: NavLink[];
}>();
</script>

<template>
  <div class="app">
    <header class="header">{{ title }}</header>
    <aside class="sidebar">
      <Link
        v-for="link in links"
        :key="link.routeName"
        :routeName="link.routeName"
        activeClassName="active"
      >
        {{ link.label }}
      </Link>
    </aside>
    <main class="content">
      <slot />
    </main>
    <footer class="footer">@real-router/vue</footer>
  </div>
</template>
