// examples/web/svelte/auth-guards/src/pages/Admin.svelte
<div>
  <h1>Admin Panel</h1>
  <p>
    This page is protected by a <code>canActivate</code> guard using
    ability-based access control. Only users with the <strong>admin</strong>
    role can access it.
  </p>
  <div class="card">
    <p>
      <strong>Access control:</strong>
    </p>
    <p>alice@example.com (Admin) — ✓ Access granted</p>
    <p>bob@example.com (Editor) — ✗ Guard blocks navigation</p>
    <p>carol@example.com (Viewer) — ✗ Guard blocks navigation</p>
  </div>
</div>

// examples/web/vue/auth-guards/src/pages/Admin.vue
<template>
  <div>
    <h1>Admin Panel</h1>
    <p>
      This page is protected by a <code>canActivate</code> guard using
      ability-based access control. Only users with the <strong>admin</strong>
      role can access it.
    </p>
    <div class="card">
      <p><strong>Access control:</strong></p>
      <p>alice@example.com (Admin) — ✓ Access granted</p>
      <p>bob@example.com (Editor) — ✗ Guard blocks navigation</p>
      <p>carol@example.com (Viewer) — ✗ Guard blocks navigation</p>
    </div>
  </div>
</template>
