// examples/react/nested-routes/src/pages/UserSettings.tsx
import type { JSX } from "react";

export function UserSettings(): JSX.Element {
  return (
    <div>
      <h1>User Settings</h1>
      <div className="card">
        <div className="form-group">
          <label>Notification Preferences</label>
          <select defaultValue="all">
            <option value="all">All notifications</option>
            <option value="mentions">Mentions only</option>
            <option value="none">None</option>
          </select>
        </div>
        <div className="form-group">
          <label>Theme</label>
          <select defaultValue="light">
            <option value="light">Light</option>
            <option value="dark">Dark</option>
          </select>
        </div>
        <button className="primary" style={{ marginTop: "8px" }}>
          Save Settings
        </button>
      </div>
    </div>
  );
}

// examples/web/vue/nested-routes/src/pages/UserSettings.vue
<template>
  <div>
    <h1>User Settings</h1>
    <div class="card">
      <div class="form-group">
        <label>Notification Preferences</label>
        <select>
          <option value="all" selected>All notifications</option>
          <option value="mentions">Mentions only</option>
          <option value="none">None</option>
        </select>
      </div>
      <div class="form-group">
        <label>Theme</label>
        <select>
          <option value="light" selected>Light</option>
          <option value="dark">Dark</option>
        </select>
      </div>
      <button class="primary" :style="{ marginTop: '8px' }">
        Save Settings
      </button>
    </div>
  </div>
</template>
