// examples/web/svelte/nested-routes/src/pages/UsersLayout.svelte
<script lang="ts">
  import { Link, RouteView, useRoute, useRouteNode, useRouteUtils } from "@real-router/svelte";
  import type { Params } from "@real-router/core";
  import UsersList from "./UsersList.svelte";
  import UserProfile from "./UserProfile.svelte";

  const routeLabels: Record<string, string> = {
    home: "Home",
    users: "Users",
    "users.profile.settings": "Settings",
  };

  function getLabel(name: string, params: Params): string {
    if (name in routeLabels) {
      return routeLabels[name];
    }
    if (name === "users.profile") {
      const id = typeof params.id === "string" ? params.id : "?";
      return `User #${id}`;
    }
    return name;
  }

  const { route: globalRoute } = useRoute();
  const utils = useRouteUtils();
  const { route } = useRouteNode("users");
</script>

{#if route.current}
  {@const chain = utils.getChain(globalRoute.current.name) ?? [globalRoute.current.name]}
  {@const crumbs = ["home", ...chain]}
  <nav class="breadcrumbs" aria-label="breadcrumb">
    {#each crumbs as name, i}
      {#if i > 0}<span> › </span>{/if}
      {#if i === crumbs.length - 1}
        <span>{getLabel(name, globalRoute.current.params)}</span>
      {:else}
        <Link routeName={name}>{getLabel(name, globalRoute.current.params)}</Link>
      {/if}
    {/each}
  </nav>

  <!--
    `users` IS the list — no synthetic `list` child / forwardTo. The `self`
    snippet renders UsersList when active route is exactly `users`; the
    `profile` snippet wins for /users/:id and deeper (UserProfile owns its
    own sub-navigation).
  -->
  <div style="margin-top: 16px;">
    <RouteView nodeName="users">
      {#snippet self()}
        <UsersList />
      {/snippet}
      {#snippet profile()}
        <UserProfile />
      {/snippet}
    </RouteView>
  </div>
{/if}

// examples/web/vue/nested-routes/src/pages/UsersLayout.vue
<script setup lang="ts">
import {
  Link,
  RouteView,
  useRoute,
  useRouteNode,
  useRouteUtils,
} from "@real-router/vue";
import { computed } from "vue";

import UserProfile from "./UserProfile.vue";
import UsersList from "./UsersList.vue";

import type { Params } from "@real-router/core";

const routeLabels: Record<string, string> = {
  home: "Home",
  users: "Users",
  "users.profile.settings": "Settings",
};

function getLabel(name: string, params: Params): string {
  if (name in routeLabels) {
    return routeLabels[name];
  }

  if (name === "users.profile") {
    const id = typeof params.id === "string" ? params.id : "?";

    return `User #${id}`;
  }

  return name;
}

const { route: usersRoute } = useRouteNode("users");
const { route } = useRoute();
const utils = useRouteUtils();

const crumbs = computed(() => {
  const chain = utils.getChain(route.value.name) ?? [route.value.name];

  return ["home", ...chain];
});
</script>

<template>
  <div v-if="usersRoute">
    <nav class="breadcrumbs" aria-label="breadcrumb">
      <template v-for="(name, i) in crumbs" :key="name">
        <span v-if="i > 0"> › </span>
        <span v-if="i === crumbs.length - 1">{{
          getLabel(name, route.params)
        }}</span>
        <Link v-else :routeName="name">{{ getLabel(name, route.params) }}</Link>
      </template>
    </nav>

    <div :style="{ marginTop: '16px' }">
      <!--
        `users` route IS the list — no synthetic `list` child / forwardTo.
        <RouteView.Self> renders UsersList when active route is exactly
        `users`; <RouteView.Match segment="profile"> wins for /users/:id and
        deeper (UserProfile owns its own sub-navigation).
      -->
      <RouteView nodeName="users">
        <RouteView.Self>
          <UsersList />
        </RouteView.Self>
        <RouteView.Match segment="profile">
          <UserProfile />
        </RouteView.Match>
      </RouteView>
    </div>
  </div>
</template>
