// examples/web/svelte/lazy-loading/src/pages/Analytics.svelte
<div>
  <h1>Analytics</h1>
  <p>
    This component was lazy-loaded in a separate chunk (parallel to
    Dashboard).
  </p>
  <div class="card">
    <p>
      <strong>Page Views:</strong> 45,230
    </p>
    <p>
      <strong>Bounce Rate:</strong> 34%
    </p>
    <p>
      <strong>Avg. Session:</strong> 2m 45s
    </p>
  </div>
</div>

// examples/vue/lazy-loading/src/pages/Analytics.vue
<template>
  <div>
    <h1>Analytics</h1>
    <p>
      This component was lazy-loaded in a separate chunk (parallel to
      Dashboard).
    </p>
    <div class="card">
      <p><strong>Page Views:</strong> 45,230</p>
      <p><strong>Bounce Rate:</strong> 34%</p>
      <p><strong>Avg. Session:</strong> 2m 45s</p>
    </div>
  </div>
</template>
