// examples/web/svelte/combined/src/pages/ProductDetail.svelte
<script lang="ts">
  import { Link } from "@real-router/svelte";
  import { store } from "../../../../../shared/store";
  import type { Product } from "../../../../../shared/api";

  let product = $state(store.get("products.detail") as Product | null | undefined);
  let loading = $state(store.get("products.detail:loading") as boolean | undefined);
  let error = $state(store.get("products.detail:error") as string | null | undefined);

  $effect(() => {
    return store.subscribe(() => {
      product = store.get("products.detail") as Product | null | undefined;
      loading = store.get("products.detail:loading") as boolean | undefined;
      error = store.get("products.detail:error") as string | null | undefined;
    });
  });
</script>

{#if loading}
  <div><h1>Product</h1><span class="spinner"></span></div>
{:else if error}
  <div><h1>Product</h1><p>Error: {error}</p><Link routeName="products">← Back</Link></div>
{:else if !product}
  <div><h1>Product</h1><p>Not found.</p><Link routeName="products">← Back</Link></div>
{:else}
  <div>
    <h1>{product.name}</h1>
    <div class="card">
      <p><strong>Price:</strong> ${product.price}</p>
      <p><strong>Description:</strong> {product.description}</p>
      <p><strong>ID:</strong> {product.id}</p>
    </div>
    <Link routeName="products">← Back to Products</Link>
  </div>
{/if}

// examples/web/react/data-loading/src/pages/ProductDetail.tsx
import { Link } from "@real-router/react";
import { useSyncExternalStore } from "react";

import { store } from "../../../../shared/store";

import type { Product } from "../../../../shared/api";
import type { JSX } from "react";

export function ProductDetail(): JSX.Element {
  const product = useSyncExternalStore(store.subscribe, () =>
    store.get("products.detail"),
  );
  const loading = useSyncExternalStore(
    store.subscribe,
    () => store.get("products.detail:loading") as boolean | undefined,
  );
  const error = useSyncExternalStore(
    store.subscribe,
    () => store.get("products.detail:error") as string | null | undefined,
  );

  if (loading) {
    return (
      <div>
        <h1>Product</h1>
        <span className="spinner" />
        <span style={{ marginLeft: "12px" }}>Loading product…</span>
      </div>
    );
  }

  if (error) {
    return (
      <div>
        <h1>Product</h1>
        <p>Error: {error}</p>
        <Link routeName="products">← Back to Products</Link>
      </div>
    );
  }

  if (!product) {
    return (
      <div>
        <h1>Product</h1>
        <p>Product not found.</p>
        <Link routeName="products">← Back to Products</Link>
      </div>
    );
  }

  return (
    <div>
      <h1>{product.name}</h1>
      <div className="card">
        <p>
          <strong>Price:</strong> ${product.price}
        </p>
        <p>
          <strong>Description:</strong> {product.description}
        </p>
        <p>
          <strong>ID:</strong> {product.id}
        </p>
      </div>
      <Link routeName="products">← Back to Products</Link>
    </div>
  );
}
