// packages/solid/src/components/HttpStatusProvider.tsx
import { createContext } from "solid-js";

import type { HttpStatusSink } from "../utils/createHttpStatusSink";
import type { JSX } from "solid-js";

export const HttpStatusContext = createContext<HttpStatusSink | null>(null);

export interface HttpStatusProviderProps {
  readonly sink: HttpStatusSink;
  readonly children: JSX.Element;
}

export function HttpStatusProvider(
  props: HttpStatusProviderProps,
): JSX.Element {
  return (
    <HttpStatusContext.Provider value={props.sink}>
      {props.children}
    </HttpStatusContext.Provider>
  );
}

// packages/preact/src/components/HttpStatusProvider.tsx
import { createContext } from "preact";

import type { HttpStatusSink } from "../utils/createHttpStatusSink";
import type { ComponentChildren } from "preact";

export const HttpStatusContext = createContext<HttpStatusSink | null>(null);

export interface HttpStatusProviderProps {
  readonly sink: HttpStatusSink;
  readonly children: ComponentChildren;
}

export function HttpStatusProvider({
  sink,
  children,
}: HttpStatusProviderProps): ComponentChildren {
  return (
    <HttpStatusContext.Provider value={sink}>
      {children}
    </HttpStatusContext.Provider>
  );
}
