// examples/web/vue/v-link-directive/src/pages/Home.vue
<script setup lang="ts">
const products = [
  { id: "1", name: "Laptop", price: "$999" },
  { id: "2", name: "Phone", price: "$699" },
  { id: "3", name: "Tablet", price: "$449" },
];
</script>

<template>
  <div>
    <h1>Home</h1>
    <p>
      The cards below use <code>v-link</code> directive on
      <code>&lt;div&gt;</code> elements — not <code>&lt;a&gt;</code> tags. Click
      any card to navigate.
    </p>

    <div
      :style="{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
        gap: '16px',
        marginTop: '16px',
      }"
    >
      <div
        v-for="product in products"
        :key="product.id"
        v-link="{ name: 'products.detail', params: { id: product.id } }"
        class="card"
        role="link"
        tabindex="0"
      >
        <strong>{{ product.name }}</strong>
        <p :style="{ color: '#888' }">{{ product.price }}</p>
      </div>
    </div>

    <div :style="{ marginTop: '24px' }">
      <h2>Other v-link elements</h2>

      <button v-link="{ name: 'checkout' }" :style="{ marginRight: '8px' }">
        Go to Checkout (button)
      </button>

      <a v-link="{ name: 'checkout' }"> Go to Checkout (anchor) </a>
    </div>
  </div>
</template>

// examples/web/solid/use-link-directive/src/pages/Home.tsx
import { link } from "@real-router/solid";
import { For } from "solid-js";

import type { JSX } from "solid-js";

// Keep reference to prevent tree-shaking (Solid directive pattern)
// eslint-disable-next-line @typescript-eslint/no-unused-expressions -- Solid directive use:link is detected at compile time but reads as unused at runtime
link;

const products = [
  { id: "1", name: "Laptop", price: 999 },
  { id: "2", name: "Keyboard", price: 79 },
  { id: "3", name: "Monitor", price: 449 },
];

export function Home(): JSX.Element {
  return (
    <div>
      <h1>Home</h1>
      <p>
        This example demonstrates <code>use:link</code> directive on different
        elements: <code>&lt;div&gt;</code>, <code>&lt;a&gt;</code>, and{" "}
        <code>&lt;button&gt;</code>.
      </p>

      <h2>Product Cards (div with use:link)</h2>
      <div
        style={{
          display: "grid",
          "grid-template-columns": "repeat(auto-fill, minmax(200px, 1fr))",
          gap: "12px",
        }}
      >
        <For each={products}>
          {(product) => (
            <div
              use:link={() => ({
                routeName: "products.detail",
                routeParams: { id: product.id },
                activeClassName: "active",
              })}
              class="card"
              style={{ cursor: "pointer" }}
            >
              <strong>{product.name}</strong>
              <p>${product.price}</p>
            </div>
          )}
        </For>
      </div>

      <h2 style={{ "margin-top": "24px" }}>Anchor with use:link (gets href)</h2>
      <a
        use:link={() => ({
          routeName: "settings",
          activeClassName: "active",
        })}
      >
        Go to Settings (anchor — gets href for SEO)
      </a>

      <h2 style={{ "margin-top": "24px" }}>Button with use:link</h2>
      <button
        use:link={() => ({
          routeName: "settings",
        })}
      >
        Go to Settings (button — no href)
      </button>
    </div>
  );
}
