// packages/solid/src/hooks/useDeferred.tsx
import { useRoute } from "./useRoute";

import type { Accessor } from "solid-js";

interface DeferredContext {
  ssrDataDeferred?: Record<string, Promise<unknown>>;
}

const NEVER_PROMISE = new Promise<never>(() => {
  // Intentionally never resolves — surfaces a forever-pending Suspense boundary
  // when a key is requested that the loader never declared.
});

/**
 * Read a deferred promise published by `defer({ deferred: { <key>: Promise } })`
 * inside an SSR data loader.
 *
 * Returns a Solid `Accessor<Promise<T>>` so the value tracks the active route
 * — re-reading on navigation picks up the new state's deferred map. Wrap with
 * `<Await name="key">{(value) => …}</Await>` (this package), which builds on
 * `createResource` + `<Suspense>` for native Solid streaming.
 *
 * Returns a forever-pending promise when the key is missing — surfaces
 * loader/consumer key drift as a visible Suspense fallback rather than a
 * silent runtime error.
 */
export function useDeferred<T = unknown>(key: string): Accessor<Promise<T>> {
  const routeAccessor = useRoute();

  return () => {
    const context = routeAccessor().route.context as DeferredContext;
    const deferred = context.ssrDataDeferred;

    return (deferred?.[key] ?? NEVER_PROMISE) as Promise<T>;
  };
}

// packages/react/src/hooks/useDeferred.tsx
import { useRoute } from "./useRoute";

interface DeferredContext {
  ssrDataDeferred?: Record<string, Promise<unknown>>;
}

const NEVER_PROMISE = new Promise<never>(() => {
  // Intentionally never resolves — surfaces a forever-pending Suspense boundary
  // when a key is requested that the loader never declared.
});

/**
 * Read a deferred promise published by `defer({ deferred: { <key>: Promise } })`
 * inside an SSR data loader.
 *
 * - **Server render**: returns the actual loader-returned promise. Combine
 *   with `<Suspense>` + `use(promise)` for native streaming via React 19's
 *   `renderToReadableStream`.
 * - **Post-hydration**: returns a registry-backed promise; the inline
 *   `<script>__rrDefer__("key", json)</script>` tags emitted by the server
 *   stream resolve it. `use()` returns synchronously once the registry
 *   settles.
 * - **Unknown key**: returns a never-resolving promise — Suspense boundary
 *   stays in fallback. This surfaces consumer/loader key drift as a visible
 *   loading state instead of a silent runtime error.
 *
 * The hook subscribes to `RouteContext`, so it re-runs on every navigation.
 * Promise reference identity is stable across renders within the same
 * navigation — `use()` will not re-suspend on rerenders.
 */
export function useDeferred<T = unknown>(key: string): Promise<T> {
  const { route } = useRoute();
  const context = route.context as DeferredContext;
  const deferred = context.ssrDataDeferred;
  const promise = deferred?.[key];

  return (promise ?? NEVER_PROMISE) as Promise<T>;
}
