// packages/solid/src/context.ts
import { createContext } from "solid-js";

import type { RouteState } from "./types";
import type { Router, Navigator } from "@real-router/core";
import type { Accessor } from "solid-js";

export interface RouterContextValue {
  router: Router;
  navigator: Navigator;
}

export const RouterContext = createContext<RouterContextValue | null>(null);

export const RouteContext = createContext<Accessor<RouteState> | null>(null);

// packages/react-router6/modules/context.ts
// packages/react-real-router/modules/context.ts

import { createContext } from "react";

import type { RouteContext as RouteContextType } from "./types";
import type { Router } from "router6";

export const RouteContext = createContext<RouteContextType | null>(null);

export const RouterContext = createContext<Router | null>(null);
